### ISSUE TITLE
Disconnecting transport while still in use

### ISSUE THREAD

**Issue by boris-petrov** [AgNO3/jcifs-ng#100]
Hi, thanks a bunch for taking the time to update and support jCIFS!

I'm trying to figure out why I get three warnings during the shutdown of our product:

```
Disconnecting transport while still in use Transport0[0.0.0.0<00>/192.168.88.182:445,state=5,signingEnforced=false,usage=1]: [SmbSession[credentials=guest,targetHost=192.168.88.182,targetDomain=null,uid=0,connectionState=2,usage=1]]
```

```
Logging off session while still in use SmbSession[credentials=guest,targetHost=192.168.88.182,targetDomain=null,uid=0,connectionState=3,usage=1]:[SmbTree[share=PUBLIC,service=null,tid=1712427064,inDfs=false,inDomainDfs=false,connectionState=2,usage=69]]
```

```
Disconnected tree while still in use SmbTree[share=PUBLIC,service=null,tid=1712427064,inDfs=false,inDomainDfs=false,connectionState=3,usage=69]
```

I'm using `jcifs-ng` via `vfs-jcifs-ng` (this is an Apache Commons VFS driver). I am cleaning everything correctly I think. Is there any easy way to figure out what am I not closing/freeing up?

**Comment by mbechler** [comment]
Setting the property _jcifs.traceResources=true_ should provide the code locations where the resources are initialized that do not get cleaned up properly. Hope that helps.

**Comment by mbechler** [comment]
close()ing SmbFile is not necessary without strictResourceLifecycle as these are not tracked at all (that's the main difference). If you properly close all file handles (+ iterators) that should be sufficient to avoid any resource leaks and the warning.

**Comment by boris-petrov** [comment]
Hi, thanks for the answers and sorry for the delay! `jcifs.traceResources=true` helped me debug some stupidity in third-party code and fix all my leaks.

I'm not sure however that I understood what `jcifs.smb.client.strictResourceLifecycle` does - setting it to true seems to print a million warnings in my case. Is this something to worry about?

**Comment by mbechler** [comment]
With strictResourceLifecycle you'll have to also close all SmbFile/SmbResource objects after use. This allows keeping the connection alive while there are still files in "use" on that connection. However, this only prevents having to reestablish a connection when calling another method on that object and should not cause any real issues, so I guess most people can ignore this option.

**Comment by boris-petrov** [comment]
Thank you very much for the support! I'll leave you to close this issue.

Perhaps these two options could be documented somewhere and maybe a link in the README would help people like me not open issues like this one. :) Thanks again!
