### ISSUE TITLE
Not an issue, just wondering if you have a time frame for the 2.1.1 release?

### ISSUE THREAD

**Issue by myoldprojects** [AgNO3/jcifs-ng#114]
My apologies, if this is not the right place to post this question.  We would like to incorporated most of the commits you have on the master branch.  Like many, thank you for all your time spend in this project.

**Comment by mbechler** [comment]
I guess I should get to that some time this or next weekend.

**Comment by mbechler** [comment]
Unfortunately, my test infrastructure is giving me quite a fight, so it will take a bit longer.
