### ISSUE TITLE
Question on NtStatus errror codes

### ISSUE THREAD

**Issue by chihaiaalex** [AgNO3/jcifs-ng#125]
We are currently using jcifs in an integration in which we need to write some files to a samba server.

I was thinking of implementing a retry logic but I can't figure it out which of the status codes
available in the NtStatus class can be retried and which of them are critical and should be considered
as unrecoverable.

Is there a documentation on this?
Can we make a clear distinction between this two types or not?

Thanks!

**Comment by mbechler** [comment]
I don't think that there is a clear distinction. The status codes even might mean different things for different request types. But there problably are not that many in which a retry could possibly succeed.
Are there any specific errors that you have encountered so far?
