### ISSUE TITLE
Tests not passing in master

### ISSUE THREAD

**Issue by tantonioli-fluxit** [AgNO3/jcifs-ng#13]
Hi, 
  Before all, thanks for your contribution, It was  just what I was looking for!

  I clone the master today and I found these errors in the tests compiling the project:

> Tests in error: 
>   PACTest.testAES256Checksum:218->verifyAESHMAC:252 » InvalidKey Illegal key siz...
>   PACTest.testPACAESChecksum:176->verifyAESMAC:229->verifyAESHMAC:252 » InvalidKey
> 
> Tests run: 31, Failures: 0, Errors: 2, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 10.039 s
> [INFO] Finished at: 2017-07-14T12:34:30-03:00
> [INFO] Final Memory: 32M/467M
> [INFO] ------------------------------------------------------------------------

  Could I be missing something?
 
  Now skiped them and I trying the lib without any trouble, but I wander if you are planning to release v2 in the short time.

Thanks!

**Comment by mbechler** [comment]
If you are using an Oracle JRE you'll have to install the JCE Unlimited Strength Jurisdiction Policy otherwise AES-256 is not allowed which is required for these tests. 

Regarding a release I was mostly waiting for feedback, there is an open bug that I'd still like to figure out before a release, but I guess it shouldn't be too much longer.

**Comment by mbechler** [comment]
And I forgot to mention, these tests are totally irrelevant for regular operations - so no need to worry at all. Some time in the future (when adding SMB3 support) unlimited JCE will probably become mandatory, but for now it isn't.

**Comment by tantonioli-fluxit** [comment]
Great! As you said installing JCE was the solution.

Thanks for your fast reponse!
