### ISSUE TITLE
NTLMv2 and SMB2

### ISSUE THREAD

**Issue by j-m-baker** [AgNO3/jcifs-ng#131]
Hello

Thank you for your work in cleaning up the original jcifs code. I see you've got SMBv2 code - will this verify NTLMv2 tokens sent by a browser? I see the original NTLM filters are marked deprecated.

Thanks

**Comment by mbechler** [comment]
No, there is no such support. The NTLMv1 stuff definitely should not be used anymore and I suppose won't work with correctly configured recent systems anyway. The hack used to perform domain based NTLM there no longer works for NTLMv2, so this needs more that switching to the new protocol message format. A netlogon client implementation is required for verifying domain credentials, which we currently don't have (actually I have implemented that before but don't have the necessary rights to just release it).

**Comment by j-m-baker** [comment]
I believe we need to connect to the Endpoint Manager and get the relevant NETLOGON port, right?

**Comment by mbechler** [comment]
It's a bit more involved, mostly because the netlogon protocol adds another layer of cryptography
