### ISSUE TITLE
SMB server connection code migrate from jcifs to jcifs-ng library 2.1.1

### ISSUE THREAD

**Issue by harisingh-highq** [AgNO3/jcifs-ng#139]
Previously i was using jcifs library for file upload and download. Now i am going to move it to jcifs-ng
library to support SMB 3 protocol.
Here is code snippet to connect smb server with jcifs library:-
`String url = "smb://domain;username:password@fileserverxxx/smb2data/directory/fileName";

SmbFile from =new SmbFile(url);

if(from.exists())
{
	//read and write the file
}`
Now just above code migrate to jcifs-ng library and it shows me the warning "The constructor SmbFile(String) is deprecated" so is there any changes to connect to smb server with username 
& password in jcifs-ng library?
Can you please provide a sample code example of smb server connection with jcifs-ng library?

**Comment by mbechler** [comment]
It is now centered around CIFSContext. As long as you don't need for example multiple configurations, or want to isolate conneciton pools you can use the SingletonContext implementation which more or less has the "shared everything" semantics of the original jcifs library. Starting from there you can create sub-contexts with credentials and then access files using that context, e.g.

```
CIFSContext base = SingletonContext.getInstance(); 
CIFSContext authed1 = base.withCredentials(new NtlmPasswordAuthenticator("mydom", "myuser, "mypass");

try ( SmbFile f = new SmbFile("smb://....", authed1) ) {
   f.exists(); // using the provided credentials
}
```

**Comment by harisingh-highq** [comment]
okay @mbechler. Let me try with above code on SMB3 protocol server.
Thanks for your quick response.
I appreciate your help.
