### ISSUE TITLE
Out of Memory caused by entries not properly removed from response_map in Transport and SmbTransportImpl

### ISSUE THREAD

**Issue by justoperez** [AgNO3/jcifs-ng#14]
I'm getting an out of memory (the max heap size is 512MB, but also happens if the heap size is 1GB). 

I see in the heap dump that 99% of the memory is held by the response_map concurrent hash map in Transport.java. Both SmbTransportImpl.java and Transport.java use the response_map.

In Transport.java, the response_map is populated like this,

this.response_map.put(k, curResp);

and items removed like this,

this.response_map.remove(curResp)

Nothing is getting removed because the remove() call should be using the key and not the curResp for the parameter.

In Transport.java, the logic also seems incorrect on the remove(). The responses are added like this,

this.response_map.put(k, resp)

and removed like this,

this.response_map.remove(req)

the key should instead be used in the remove here as well.

Is this a known issue? I wonder why it hadn't been seen before? Does the hashmap tend to grow bigger when doing big files and hence it's the reason it this not always seen?

Or maybe I'm missing something from reading the code?

Thanks.

**Comment by mbechler** [comment]
You are right, that definitely is very wrong and should happen for anybody. I guess that just hasn't grown large enough for anyone else yet to actually notice the leak, looks like that was introduced with 2.0. Will fix that and do a release asap.

**Comment by mbechler** [comment]
jcifs-ng-2.0.2 released. should arrive on maven central shortly.
