### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by Guiorgy** [AgNO3/jcifs-ng#142]
> Libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose.

source: [here](https://www.slf4j.org/codes.html#StaticLoggerBinder)

**Comment by mbechler** [comment]
jcifs-ng does not declare a dependency on a logger implementation (or rather only for testing). This error likely occurs exactly because you don't have any logger implementation on your classpath.

**Comment by Guiorgy** [comment]
I am on androi so it should have it's own logger though?

**Comment by mbechler** [comment]
You'll need a binding between that and the SLF4J API. There does not seem to be a maintained direct way of doing that so you probably need to pull in logback or log4j as an intermediate.
