### ISSUE TITLE
connTimeout doesn't terminate

### ISSUE THREAD

**Issue by Guiorgy** [AgNO3/jcifs-ng#143]
```java
Properties properties = new Properties();
properties.setProperty("jcifs.smb.client.domain", serverIP);
properties.setProperty("jcifs.netbios.wins", serverIP);
properties.setProperty("jcifs.smb.client.responseTimeout", "50");
properties.setProperty("jcifs.smb.client.soTimeout", "15000");
properties.setProperty("jcifs.smb.client.connTimeout", "50");
properties.setProperty("jcifs.smb.client.sessionTimeout", "15000");
properties.setProperty("jcifs.netbios.soTimeout", "15000");
properties.setProperty("jcifs.netbios.retryCount", "1");
properties.setProperty("jcifs.netbios.retryTimeout", "20");
properties.setProperty("jcifs.smb.client.minVersion", "SMB1");
properties.setProperty("jcifs.smb.client.maxVersion", "SMB311");
```
and then
```java
Log.d("SMB", "before");
SmbFile[] files = root.listFiles(fileFilter);
Log.d("SMB", "after");
```
and it never goes past the listFiles. (doesn't enter the catch block either, so no Exception)

PS. jcifs-ng: 2.1.1
system: Android 6.0.1 (API 23)

**Comment by mbechler** [comment]
Please provide a thread dump (stacktraces of all relevant threads + locks held if possible) in the locked up state.

Note: your responseTimeout and connTimeout are awfully low

**Comment by Guiorgy** [comment]
> your responseTimeout and connTimeout are awfully low

Originally they were 5000, I set them low to recreate the problem. The first time I run into the problem, is when I accidentally connected to a different network that, therefore had no access to the shared server, so it should have timed out, but the app stoped responding...

as for the rest, I'll try on monday.

**Comment by Guiorgy** [comment]
[memory-20190304T143708.zip](https://github.com/AgNO3/jcifs-ng/files/2925962/memory-20190304T143708.zip)

Do mind, that I haven't really dealt with thread dumps, so if I did anything wrong, please do point me to a place with more info.

**Comment by mbechler** [comment]
Thanks, the dumps were helpful. I think I found the deadlock, should be fixed in master.

**Comment by Guiorgy** [comment]
will try tomorow.

**Comment by Guiorgy** [comment]
So far, it's working like a charm. I'll be closing the issue.
