### ISSUE TITLE
Question: How get Netbios name?

### ISSUE THREAD

**Issue by Kitsune2222** [AgNO3/jcifs-ng#145]
How get local network devices netbios (server) name with this library?

**Comment by mbechler** [comment]
The library does not have provisions to get the actual netbios name from the system. For all purpose the library itself uses a hostname configured by _jcifs.netbios.hostname_. If you want to get that you can do so through NameServiceClient which can be obtained from the context object.

**Comment by Kitsune2222** [comment]
i'm found:
val cifsContext = BaseContext(PropertyConfiguration(System.getProperties())).withGuestCrendentials()
val hostName = cifsContext.nameServiceClient.getNbtAllByAddress(ipAddress)[0].name.name
this works
