### ISSUE TITLE
How to test file read/write program using jcifs-ng library with SMB2 protocol disabled and only SMB3 protocol enabled on server 

### ISSUE THREAD

**Issue by harisingh-highq** [AgNO3/jcifs-ng#146]
I want to test jcifs-ng library with SMB3 protocol server.
As i have performed below steps:-
1)Perform powershell command "Set-SmbServerConfiguration -EnableSMB2Protocol $true" to enable SMB2 protocol on windows 2016 server.
2)Performed "Get-SmbServerConfiguration" powershell command to check SMB protocol version on server
![image](https://user-images.githubusercontent.com/33862788/53725925-f6e71f00-3e92-11e9-99fc-231cca6f276f.png)
3)Execute java program with below code:-
String url = "smb://fileserverind1.hqdev.india/sharedata/hari/123.pdf";
`CIFSContext base = SingletonContext.getInstance();
CIFSContext authed1 = base.withCredentials(new NtlmPasswordAuthentication(base, "", "username", "password"));
try ( SmbFile f = new SmbFile(url, authed1) ) 
{
    if(f.exists())
    {
           System.out.println("file exist");
    }
}`

As per above steps, its working fine and print "file exist" message successfully.
But if i disable SMB2 protocol with command "Set-SmbServerConfiguration -EnableSMB2Protocol $false" then above program not working fine. So now how do i confirm that if SMB2 protocol is disabled on server and only SMB3 protocol is enabled on server, in this condition jcifs-ng library supported or not?

**Comment by mbechler** [comment]
SMB3 dialects are supported but not (yet) enabled by default, you'll have to set jcifs.smb.client.maxVersion=SMB300 (or SMB302, SMB311) to enable it.

**Comment by fataiamoranbiniitpeople** [comment]
mbechler, following your immediate suggestion, I am trying to use the code below to access a Unix Server across NetApp and I am still having "Access Denied" error:

System.setProperty ("jcifs.smb.client.maxVersions", "SMB311");

CIFSContext base = SingletonContext.getInstance(); 
        CIFSContext authed1 = base.withCredentials(new NtlmPasswordAuthenticator("xxxxx", "xxxxx", "xxxxx"));
        String url = "smb://servern/share";
		
		 try
        {        	
        	SmbFile f = new SmbFile(url, authed1);

        	for (SmbFile fi : f.listFiles()) 
        	{ 
        	    System.out.println(fi.getName());
        	} 
        }
        catch (Exception e) 
        {
			e.printStackTrace();
	}

This code works perfectly for a Windows Server (which obviously doesn't need a NetApp). I would appreciate any help with making it SMB Version 311/300 compatible. Thanks

**Comment by fataiamoranbiniitpeople** [comment]
Never mind. I found out the code specified above actually works. I was then having a credentials issue which was fixed.
