### ISSUE TITLE
pom.xml is error

### ISSUE THREAD

**Issue by yidemo** [AgNO3/jcifs-ng#153]
<osgi.version>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}.${osgi-version-qualifier}</osgi.version>
		<osgi.pkg.version>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}</osgi.pkg.version>cant find

**Comment by mbechler** [comment]
Sorry, i don't get what the issue is, can you elaborte further?
