### ISSUE TITLE
Domain name expansion problem.

### ISSUE THREAD

**Issue by VTommy** [AgNO3/jcifs-ng#155]
Hello.
I'm currently find something interesting: if the original URI of the remote resource folder is `smb://resource/Shared/common`, in some workstations, it will fail with `jcifs.smb.SmbException: Failed to connect to server`. However, this failure is flaky, as it won't happen in other workstations, thought all those workstations are in the same network with the same operating system `Ubuntu 16.04.4 LTS`.
After a few recreational investigations, I found that it is the domain name resolve problem. 
In some workstations, there is a search record in `/etc/resolve.conf` stating `search office.company.com`. Meanwhile, the domain name of the smb server is `resource.office.company.com`.
So it's pretty much a domain name resolve problem, as `smb://resource.office.company.com/Shared/common` works on those workstations where the failure exists previously.
But, I don't think hardcoding the full domain name is a good idea, as we already employed it once in `NtlmPasswordAuthenticator`. It might be a bad practise to keep info duplicated. So is there any build-in functionality in `jcifs-ng` to handle the domain expansion task before going to resolve phase?

**Comment by mbechler** [comment]
What is your expectation there? 
DNS resolving is done by the Java/ Runtime or the OS, and I don't think we should fiddle with that.
If this worked before then either the resolver was correctly configured, or netbios was used (this we might figure out why it may have worked before and not now)
What's the issue with specifying the proper domain name twice?
