### ISSUE TITLE
copyTo() fails when source and destination paths have same share name

### ISSUE THREAD

**Issue by zshtern** [AgNO3/jcifs-ng#157]
We found in our tests that following code will consistently fail in copyTo() call:

_SmbFile localFile = new SmbFile("server1" + "/ShareName/anyDirectory/a.file", cifsContext);
if (localFile.exists() && localFile.isFile()) {
   if (localFile.canRead()) {
       SmbFile remoteFile = new SmbFile("server2" + "/ShareName/anyDirectoryEither/a.file", cifsContext);
       localFile.copyTo(remoteFile);
   }
}_

Root cause seems to be in wrong implementation of isSameTree():
        _if ( sh.isSMB2() && dh.isSMB2() && sh.isSameTree(dh) )_ 
which does not take into account host information.

**Comment by mbechler** [comment]
Good catch, I don't think server side copy would work across different sessions, so the check needs to be even a bit more strict. Should be fixed in master.

**Comment by zshtern** [comment]
> Good catch, I don't think server side copy would work across different sessions, so the check needs to be even a bit more strict. Should be fixed in master.

Thank you for the prompt fix! When do you plan to release next stable version? Will this change be included in it?

**Comment by mbechler** [comment]
Relase with the fix should arrive on maven central shortly.
