### ISSUE TITLE
Can get total share space?

### ISSUE THREAD

**Issue by Kitsune2222** [AgNO3/jcifs-ng#159]
If library it not support, can you please add this function or no? Now i'm only can get free space, but I wan't use more statistic about share.

**Comment by mbechler** [comment]
There is length() (used space) and getDiskFreeSpace().

**Comment by hello-willy** [comment]
> There is length() (used space) and getDiskFreeSpace().

length() return 0 when the file is directory.

**Comment by Kitsune2222** [comment]
> > There is length() (used space) and getDiskFreeSpace().
> 
> length() return 0 when the file is directory.

Call length() in root directory of share. It's return used space
