### ISSUE TITLE
caching out of band discovery results using jcifs-ng NameServiceClientImpl

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#163]
In our open-source Android video application (nova), we are implementing an out of band discovery mechanism and we would like to cache the results of these queries using jcifs-ng internal caching mechanism.

What would be desirable on our side is get access to an explicit public api for externally feeding the cache, and an interface for a callback to trigger the out of band discovery mechanism in case of cache miss.
We currently use cacheAddress from NameServiceClientImpl which is package private.
The issue we face is that is does not cover all of our use cases, in particular resolving names is not performed if the codepath does not call explicitly the discovery. 

Before investing further in a solution of our own on top of jcifs-ng, we were wondering if you had any advice or plans for such a feature/change.

Would you be open to consider a PR for this?

**Comment by mbechler** [comment]
Adding a supported API for this purpose feels a bit specific, but I would definitely be open to refactoring the nameservice client so that what you need could be done more easily by extending or wrapping it. Would that work for you?

**Comment by courville** [comment]
Thanks. We found another way of dealing with the out of band discovery that does not need for now this modification. I thus close the issue.
