### ISSUE TITLE
NameServiceClientImpl does not use BCAST for name resolution

### ISSUE THREAD

**Issue by Sentaroh** [AgNO3/jcifs-ng#164]
I am configuring a virtual machine with VirtualBox on Windows 7. When virtual network adapter is enabled, the address of virtual network adapter is returned by name resolution from Android terminal.
  Windows 7 IP Address: 192.168.200.128
  VirtualNetwork Adapter IP Address: 192.168.56.1

I thought that nameServiceClientImpl # getByName (Name name, InetAddress addr) and addr are not to resolve in BCAST if it is a broadcast address.
-if (addr! = null) {/ *
+ if (addr! = null && addr! = this.baddr) {/ *
In our environment we could resolve the name.
Is this way correct?

Test code:
        NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "","android","pswd");
        CIFSContext ct = bc.withCredentials(creds);
    	String addr=bc.getNameServiceClient().getByName("SEN-HOME").getHostAddress();

My Application Log
D I 2019/05/13 18:53:05.518 SLF4J            [Trace] jcifs.netbios.NameServiceClientImpl Resolver order is [RESOLVER_LMHOSTS, RESOLVER_DNS, RESOLVER_BCAST] 
D I 2019/05/13 18:53:05.534 SLF4J            [Trace] jcifs.netbios.NameServiceClientImpl NameQueryRequest[nameTrnId=1,isResponse=false,opCode=QUERY,isAuthAnswer=false,isTruncated=false,isRecurAvailable=false,isRecurDesired=true,isBroadcast=true,resultCode=0x0,questionCount=1,answerCount=0,authorityCount=0,additionalCount=0,questionName=SEN-HOME<20>,questionType=NB,questionClass=IN,recordName=null,recordType=0x0000,recordClass=0x0000,ttl=0,rDataLength=0] 
D I 2019/05/13 18:53:05.534 SLF4J            [Trace] jcifs.netbios.NameServiceClientImpl 0001011000010000000000002046444546454F434E45494550454E4546434143414341434143414341434143410000200001 
D I 2019/05/13 18:53:05.546 SLF4J            [Trace] jcifs.netbios.NameServiceClientImpl NetBIOS: new data read from socket 
D I 2019/05/13 18:53:05.547 SLF4J            [Trace] jcifs.netbios.NameServiceClientImpl NameQueryResponse[nameTrnId=1,isResponse=true,opCode=QUERY,isAuthAnswer=true,isTruncated=false,isRecurAvailable=false,isRecurDesired=true,isBroadcast=false,resultCode=0x0,questionCount=0,answerCount=1,authorityCount=0,additionalCount=0,questionName=null,questionType=0x0000,questionClass=IN,recordName=SEN-HOME<20>,recordType=NB,recordClass=IN,ttl=300000,rDataLength=12,addrEntry=[Ljcifsng212.netbios.NbtAddress;@7386d55] 
D I 2019/05/13 18:53:05.547 SLF4J            [Trace] jcifs.netbios.NameServiceClientImpl 0001850000000001000000002046444546454F434E45494550454E4546434143414341434143414341434143410000200001000493E0000C0000C0A8C8800000C0A83801 
D I 2019/05/13 18:53:05.547 FileList         resolveHostName Name=SEN-HOME, IP addr=192.168.56.1

**Comment by mbechler** [comment]
Is the log with our without the change? What happens without it? As far as I can tell that code path should still send the NBNS request. With the change you are running the whole resolver stack again, which I guess should happen in a outer method call (a stacktrace of the call would be great, too).

**Comment by Sentaroh** [comment]
The extra part (D I YYYY/MM/DD HH: MM: SS.ttt SLF4J) has been added because the log gets the data from SLF4J and outputs it in the Android app.
I would like to change the parameters of getNbtByName () as advised.

Current:
String addr=bc.getNameServiceClient().getByName("sen-home").getHostAddress();
Changed:
String addr=bc.getNameServiceClient().getNbtByName("sen-home", 0x20, null,null).getHostAddress();

Thanks.
