### ISSUE TITLE
NPE in registerSmbURLHandler with >Java 8

### ISSUE THREAD

**Issue by Martin0815123** [AgNO3/jcifs-ng#167]
Hi, 

`calling jcifs.Config.registerSmbURLHandler();` with Java > 8 throws a Exception because the new Java-Version-Syntax is not compatible with this code:
`float ver = Float.parseFloat(Runtime.class.getPackage().getSpecificationVersion());`

Maybe we can change this code do fit newer Java-Versions?
Suggestion:
Instead of 
`float ver = Float.parseFloat(Runtime.class.getPackage().getSpecificationVersion());`
      `  String vendor = System.getProperty("java.vendor.url");`
      `  if ( ! ( vendor != null && vendor.startsWith("http://www.android.com") ) && ver < 1.7f ) {`
          `  throw new RuntimeCIFSException("jcifs-ng requires Java 1.7 or above. You are running " + ver);`
      `  }`

maybe this is better:

`String vendor = System.getProperty("java.vendor.url");`
     `   if (!(vendor != null && vendor.startsWith("http://www.android.com"))) {`
            // Java 8: example 1.8.0_181 (discart, major, minor, update build)
            // Java 9: $MAJOR.$MINOR.$SECURITY
            // Java 11: $FEATURE.$INTERIM.$UPDATE.$PATCH
        `    String versionString = System.getProperty("java.version");`
         `   String[] javaVersionElements = versionString.split("\\.|_|-b");`
 // maybe we get 12-ea (for early access versions)
          `  int major = Integer.parseInt(javaVersionElements[0].replaceAll("\\D", ""));`
          `  if (major == 1) { // <= Java 8 (1.7.., 1.8..)`
             `   major = Integer.parseInt(javaVersionElements[1]);`
             `   if (major < 7) {`
                  `  throw new RuntimeCIFSException("jcifs-ng requires Java 1.7 or above. You are running " + versionString);`
              `  }`
           ` }`
      `  }`

Can someone check this?

Another Option is to disable this Java 7 check via a setting!

Many thanks!

P.S. Sorry I do not get the code formatting right here.

**Comment by mbechler** [comment]
I just removed the check, seemed easier and I don't think there should be much Java 7 around any more.

**Comment by Martin0815123** [comment]
Thanks, yes it is easier, faster an better!
