### ISSUE TITLE
Handle not properly released when running with jcifs.smb.client.enableSMB2=false

### ISSUE THREAD

**Issue by justoperez** [AgNO3/jcifs-ng#17]
Hello. Thank you for all your help so far!

We are facing another issue when we run against a Windows 2008 server that has both SMB1 and SMB2 enabled. 

When we run with jcifs.smb.client.enableSMB2=false to test SMB1 we we get a bunch of "handle not properly released" warnings. These warnings happen in SmbTreeHandleImp.java (finalize) as well as in SmbFileHandle.java (finalize) and SmbTreeConnection.java (finalize).

We DO NOT get these warnings if we run with jcifs.smb.client.enableSMB2=true.

I decided to focus on the SmbTreeHandleImpl.java "not properly released" warnings and I debugged thru the jcifs-ng code. This what I found.

1. It seems to happen when calling SmbFile.setOwner(x). 

2. With jcifs.smb.client.enableSMB2=false, an SmbFileHandleImpl gets created and the SmbFileHandleImpl constructor increases the SmbTreeHandleImpl usage_cnt by 1. 

this.tree = tree.acquire();

This extra acquire() does not seem to ever call a matching release(). Here is the stack trace (the line numbers correspond to my version of SmbTreeHandleImpl.java since I added some warning messages. I've included my version of this file). 

Notice how we call SmbFile.openUnshared() and flow down from there until SmbFileHandleImpl() gets created.

siqsmb1.out:[2017-11-27 15:28:35,847] WARN  [1553755675@qtp--541248251-0] jcifs.smb.SmbTreeHandleImpl SmbTreeHandleImpl: Acquire SmbTreeHandleImpl smb://9.30.60.45/thanhvn/export-dat-smb2/Export_0483f65b-b36c-4de7-bcfc-a6a7175259b6/1/f490d0027a4745cb92eb9bfb51a3fa8c/documents/1/People(low confidence).doc [tree_connection_id=1214645987, usage_cnt=2], object id = -140456672. Stack trace: [java.lang.Thread.getStackTraceImpl(Native Method), java.lang.Thread.getStackTrace(Thread.java:1117), jcifs.smb.SmbTreeHandleImpl.acquire(SmbTreeHandleImpl.java:181), jcifs.smb.SmbFileHandleImpl.<init>(SmbFileHandleImpl.java:119), jcifs.smb.SmbFile.openUnshared(SmbFile.java:755), jcifs.smb.SmbFile.openUnshared(SmbFile.java:710), jcifs.smb.SmbFile.setOwner(SmbFile.java:2506), storediq.siqcifs.facade.BaseSmbFacade.setSecurityDescriptor(BaseSmbFacade.java:881), storediq.siqcifs.httpserver.httpcommands.SetSecurityDescriptorCommand.call(SetSecurityDescriptorCommand.java:46)

3. With jcifs.smb.client.enableSMB2=true, the SmbTreeHandleImpl.java call to setOwner() is a little bit different. It never goes into SmbFile.openUnshared(), I assume because it goes into the this.isSMB2() portion of the code below,

public int setOwner(SID owner) throws IOException {
        try ( SmbTreeHandleImpl th = ensureTreeConnected() ) {
            if ( th.isSMB2() ) {
                Smb2SetInfoRequest req = new Smb2SetInfoRequest(this.getContext().getConfig());
                req.setInfoType(Smb2Constants.SMB2_0_INFO_SECURITY);
                req.setFileInfoClass((byte) 0); // must be set to 0 when setting security info.
                req.setAdditionalInformation(SecurityInfo.OWNER_SECURITY_INFO);
                Smb2SetInfoResponse resp = withOpen(th, req);
                return resp.getErrorCode();
            }
        }

        int f = openUnshared(O_RDWR | O_EXCL, WRITE_DAC | WRITE_OWNER, 0,  
                    SmbConstants.FILE_SHARE_READ | SmbConstants.FILE_SHARE_WRITE, 
                            isDirectory() ? 1 : 0x4000).getFid();

Any help you can provide would be greatly appreciated. If you have any questions please let me know.

Thanks.

[SmbTreehandleImpl_modified.zip](https://github.com/AgNO3/jcifs-ng/files/1507482/SmbTreehandleImpl_modified.zip)

**Comment by mbechler** [comment]
So I guess this is a somewhat patched version, because the stock version currently does not have the setSecurity stuff. 

If you'd like to get that stuff merged, I'd be happy to look into that.

But I think the problem is simple:
```
    int f = openUnshared(O_RDWR | O_EXCL, WRITE_DAC | WRITE_OWNER, 0,  
                SmbConstants.FILE_SHARE_READ | SmbConstants.FILE_SHARE_WRITE, 
                        isDirectory() ? 1 : 0x4000).getFid();
```
discards the file handle object returned by openUnshared, that will keep the tree handle open as well (that's more or less why the reference counting mechanism is there). The close that properly, you will have to change that

```
    try ( SmbFileHandleImpl f =  openUnshared(O_RDWR | O_EXCL, WRITE_DAC | WRITE_OWNER, 0,  
                SmbConstants.FILE_SHARE_READ | SmbConstants.FILE_SHARE_WRITE, 
                        isDirectory() ? 1 : 0x4000)) {

       // existing code here, use f.getFid()
   }
```

**Comment by justoperez** [comment]
Thank you very much for your suggestion. That fixed the issue.

I'm not sure what you mean by "So I guess this is a somewhat patched version, because the stock version currently does not have the setSecurity stuff"? 

We have not patched the jcifs-ng code. It is the same stock version that we downloaded from https://github.com/AgNO3. If by setSecurity you mean the portion of the stack trace that reads "storediq.siqcifs.facade.BaseSmbFacade.setSecurityDescriptor()", that is our part of the code that calls the jcifs-ng SmbFile.setOwner() API. 

The SmbFile.setOwner() code that I pasted in my previous comment is from the stock version of SmbFile.java and we have not made any changes to it.

I did make the change you suggested in SmbFile.setOwner() and place the SmbFileHandleImpl inside the try resource statement. That solved it.

Can you review the change I made to SmbFile.java and merge it to the stock version if it looks good. I've include the modified SmbFile.java (with my changes) and the stock version in the attached zip file.

Let me know if you have any questions or concerns..

Thanks.

[SmbFile.zip](https://github.com/AgNO3/jcifs-ng/files/1511283/SmbFile.zip)

**Comment by mbechler** [comment]
That is definitely not part of the stock repository, compare
[SmbFile.java#L2407](https://github.com/AgNO3/jcifs-ng/blob/62586d7028d654d888ad909883792729941ba934/src/main/java/jcifs/smb/SmbFile.java#L2407)

That looks like an adapted version of the patches at https://github.com/siq/jcifs/

I think there are a couple of other issues with the code (e.g. I don't think that the SMB2 code actually does anything and the close() for SMB1 is redundant and might cause an error).

We can look into merging that functionality (and maybe while we are at it some more of the security setting stuff as well), but that is going to require a bit more effort and thought.

**Comment by justoperez** [comment]
My apologies. After discussing with my colleagues I now understand your comments. Yes, we added some custom code to SmbFile.java. 

We are currently discussing whether to ask for this functionality to be merged into the stock version. But as you mentioned, that might require more effort and thought.

For now, the fix you proposed solves the issue in our version of SmbFile.java. I'm closing this issue and if we decide that we would like you to consider adding security setting functionality, I will open a separate issue.

Thanks for your help.
