### ISSUE TITLE
Smb Finalizers cause 'potential' issues in heavy loaded systems

### ISSUE THREAD

**Issue by mrmrjohnjohn** [AgNO3/jcifs-ng#171]
I have been using jcifs-ng in a heavily loaded system and found large memory usage. 

When investigating the issue I noticed a lot “finalizer”’ objects hanging around. I got this usage list by looking at the “dominator tree” in the Eclipse Memory Analyser.  

Most of the finalizer objects in the list (objects waiting to be finalized) hold a reference to SMBFile, SMBTree objects. 

I believe the memory spikes are caused by the “Finalizer” thread, which is low priority, and cannot process the queue faster than “new” items added. I am create lots SmbFile for directories and files.

See - https://plumbr.io/blog/garbage-collection/debugging-to-understand-finalizer

Looking at the jcifs code I see a lot of finalizers that are just logging. Are these required for production releases of the library? Can they be removed?

Or I am using the library wrong? I am creating an SmbFile for each directory, sub-directory and file and there are potential a lot of them in existence at the same time.

**Comment by mbechler** [comment]
No, your usage is right. Didn't think about this, this is likely causing quite bad GC behavior as well. The main culprit should be SmbFile, there should not be that many SmbTree instances around and these should be long lived. 
The finalizers are mostly to help people figure out when they are leaking resources, which might be quite bad, too.  But in the case of SmbFile this is not that relevant (only for the strict resource mode, which I don't think anyone is really using), so I think we can somewhat safely remove that.

**Comment by mrmrjohnjohn** [comment]
From the analysis the other culprit was SmbTreeConnection (not SmbTree). Is this finalizer safe to remove too?
I have tried to attached a snippet from the tree.

![finalize_tree](https://user-images.githubusercontent.com/52534373/60686136-f9886e00-9e9e-11e9-8424-5864bf475f82.PNG)

Another question about resources. When looking at some example code I could see you was caching the BaseContext for use by multiple SmbFiles. Is this the preferred usage? We are creating new ones everytime: -

  if (isSMB2) {
            Properties p = new Properties();
            p.setProperty("jcifs.smb.client.minVersion", "SMB202");
            p.setProperty("jcifs.smb.client.maxVersion", "SMB210");
            p.setProperty("jcifs.smb.client.signingEnforced", "false");
            p.setProperty("jcifs.smb.client.useSMB2Negotiation", "true");
            bc = new BaseContext(new PropertyConfiguration(p));
        } else {
            bc = new BaseContext(new BaseConfiguration(true));
        }
        this.auth = FileHelper.getNTLMAuth(bc, username, password);
        bc = bc.withCredentials(auth);
        String location = url;
        if (!location.endsWith("/")) {
            location = location + "/";
        }
        this.file = (auth != null) ? new SmbFile(location, bc) : new SmbFile(location);

Any advise would be appreciated.

Also, when do you plan to release the finalizer changes?

**Comment by kimmerin** [comment]
Actually there is a memory leak lurging in [AbstractCIFSContext](https://github.com/AgNO3/jcifs-ng/blob/c73d0ba3c073dd355dd7d1c224f666358e08cd9e/src/main/java/jcifs/context/AbstractCIFSContext.java#L44)

If you don't call close on it the instance of that context never gets finalized because it's been added as shutdown hook which is a regular reference and therefor will never be cleaned up by the garbage collector. We had this issue with a high load system where we ended up with gigabytes of memory allocated, 95% of it being threads in the list of shutdown hooks in the VM.

**Comment by mbechler** [comment]
Removing that one will have a more noticeable impact, as it removes the more immediate notice that the resource has not been closed properly. This will keep the attached tree/session/connection alive and only be noticed when the connection is shutdown forcibly. We might be able to add a mode switch there, let me think about that a bit more.

Regarding the BaseContext, you'd definitely want to reuse that if you don't have a good reason not to (e.g. different configurations). Starting from there it is fine to create diffrent sub-contexts with different credentials. The base context ties together things like memory buffer reuse, connection reuse and nameservice caching.

**Comment by mrmrjohnjohn** [comment]
Did you have the opportunity to think about adding a mode switch for the SmbTreeConnection finalizer?

**Comment by mrmrjohnjohn** [comment]
Do you have any update on this issue?

**Comment by mbechler** [comment]
The SmbTreeConnection finalizer should now only be active if jcifs.traceResources is enabled.
