### ISSUE TITLE
NtlmPasswordAuthenticator public constructor with userInfo

### ISSUE THREAD

**Issue by Condor70** [AgNO3/jcifs-ng#172]
I just converted one of my projects from jcifs to jcifs-ng.

The only issue I had was that I couldn't convert:
`SmbFile file = new SmbFile(filename, new NtlmPasswordAuthentication(userInfo));`
to
`SmbFile root = new SmbFile(filename, SingletonContext.getInstance().withCredentials(new NtlmPasswordAuthenticator(userInfo, null, null, null)));`

Could you please make that particular constructor **public**?
`protected NtlmPasswordAuthenticator ( String userInfo, String defDomain, String defUser, String defPassword ) {`

**Comment by mbechler** [comment]
Is there a special reason for you to use that userinfo format?
I'm not sure I want to have that be part of the public API as I was planning ahead to maybe get rid of the user/password specification in URLs in general at some point in time.

You could get access by subclassing, however please also note that this will not result in the  behavior as the old call as it does not take into account the domain/user/password that may be configured through a property.

**Comment by Condor70** [comment]
It is an old application that stores a list of locations with the required userInfo in a database. If I would write this now then I would split out username, password and domain in separate fields. So this request is just to make backward compatibility with jcifs better.

Why would you want to get rid of userInfo support in urls? It is part of RFC 3986. You can't just deviate from a standard.

**Comment by mbechler** [comment]
There is also the deprecated NtlmPasswordAuthentication ( CIFSContext tc, String userInfo ), which is the equivalent of what you used before.

As for userinfo in general:
First, the way this was implemented as a strange mix of global and local configuration. Fixing that would likely be causing more problems than removing it.
Secondly, I feel it is a misrepresentation of how these credentials are really are used, this establishes sessions with possibly multiple servers (DFS) and not only related to the resource access.
Third, I think having the credentials in the URLs used internally is a bad idea, these are copied around alot, might be logged, etc...
