### ISSUE TITLE
Existing file not truncated when copying file with same name via SMB2

### ISSUE THREAD

**Issue by colbpatr** [AgNO3/jcifs-ng#173]
Using SMB2 to copy a file from one location to another with an already existent file with the same name results in a corrupt file, if the copied file is smaller than the original file at the target location.

Example:
file to copy: S1/d$/test.txt (Content: "Hello!")
original file at target location: S2/d$/test/test.txt (Content: "Hello World!")
file at target location after copy: S2/d$/test/test.txt (Content: "Hello!World!")

As should be obvious form the above example, the truncation of the target file seems to be missing.
The code used in this example uses two SmbFile objects pointing to the respective locations and a simple copyTo call:
```java
SmbFile sourceFile;
SmbFile destinationFile;
...
sourceFile.copyTo(destinationFile);
```

**Comment by mbechler** [comment]
Thanks for the report. Should be fixed in master.
