### ISSUE TITLE
Cannot rename between different trees

### ISSUE THREAD

**Issue by rconoverq** [AgNO3/jcifs-ng#180]
I just updated to JCIFS-NG 2.1.3 and some of my unit test that were passing started to fail  with this error:

  jcifs.smb.SmbException: Cannot rename between different trees

	at jcifs.smb.SmbFile.renameTo(SmbFile.java:1331)
	at jcifs.smb.SmbFile.renameTo(SmbFile.java:1303)
	at ...FileUtilsTest.testRenameWithSmbFile(FileUtilsTest.java:243)
        ...

I would like to have my users interact with a wrapping API that takes two files to perform a rename.  However, with this update it seems that I do not understand how the context or trees work.  I assume that if my users pass into my API two files on the same share that some how I should set one to use the same context or tree of the other before doing the rename to avoid this error.  Can someone help me understand the JCIFS-NG API better in regards to renaming files on the same share?  I already searched through the tests and could not find anything that helped me understand the reasoning behind this error.

I would like my API to look like:

  FileUtils.renameTo(final WrappedSmbFile source, final WrappedSmbFile dest);

I my method I called:

  source.renameTo(dest); 

Here is an example I created for this post the throws the same error:

    @Test
    public void testRenameWithSmbFile() throws IOException {
        //setup
        String fileNameToMove = ((Long) System.currentTimeMillis()).toString() + ".txt";
        String filePathToMove = rootFolder.getPath();
        String file = filePathToMove + fileNameToMove; //file to move

        CIFSContext sourceContext = new BaseContext(new BaseConfiguration(true));
        CIFSContext destContext = new BaseContext(new BaseConfiguration(true));

        sourceContext = sourceContext.withCredentials(new NtlmPasswordAuthenticator(SHARE_USER, SHARE_PASSWORD));
        destContext = destContext.withCredentials(new NtlmPasswordAuthenticator(SHARE_USER, SHARE_PASSWORD));

        SmbFile source = new SmbFile(file, sourceContext);
        if (!source.exists()) {
            source.createNewFile();
        }
        String newPath = rootFolder.getPath() + "subFolder1" + "/"; //destination directory path
        NetFile destinationFolder = new NetFile(newPath, SHARE_USER, SHARE_PASSWORD);
        if (!destinationFolder.exists()) {
            destinationFolder.mkdir();
        }

        SmbFile renamedFile = null;
        try {
            //exercise
            SmbFile dest = new SmbFile(newPath + fileNameToMove, destContext);
            source.renameTo(dest);

            //assert
            renamedFile = new SmbFile(newPath + fileNameToMove, sourceContext);
            assertFalse(source.exists());   //file was moved
            assertTrue(renamedFile.exists());     //file was moved
        } finally {
            //clean up
            if (renamedFile != null && renamedFile.exists()) {
                renamedFile.delete();
            }
            if (destinationFolder.exists()) {
                destinationFolder.delete();
            }
        }
    }

I played around with the above example and figured out that I could get the rename to pass if  I used that same context for source and dest.  However, I don't want my users to have to think about that.  Is there a way to check the source and dest files passed into my API to see if they are pointed to the same server and set the dest context to the source context before doing the rename?  Or what is the best way to hide the details in my API using JCIFS-NG without the error?

Or is this a bug that was introduce in 2.1.3?

**Comment by mbechler** [comment]
This was introduced by the fix of the isSameTree method in 2.1.3. As this method is also used in deciding whether server-side copy can be used this has somewhat stricter preconditions.
Renaming is using just the UNC path for the target, being as strict would not be necessary there,  although the renameTo method generally has somewhat dubious semantics I guess.

If you just want to it to behave like before something along the lines of
`SmbFile adjusteddest = new SmbFile(dest.getURL(), src.getContext());`
should work.

But, in general, you'd really want to reuse the BaseContext instances if you don't have a good reason not to (e.g. different configurations). Otherwise you won't get any connection reuse, which will cause really bad performance and you'll easily hit connection limits on some servers.

If you do, and the same session is used (same base context + same credentials), you should end up with the same tree connection making this just work as expected.

**Comment by rconoverq** [comment]
So, added to my code something like:

if (src.getServer().equals(dest.getServer()))
                    && src.getShare().equals(dest.getShare()))
                    && src.getContext().getCredentials().getUsername().equals(dest.getSmbFile().getContext().getCredentials().getUsername())
                    && src.getContext().getCredentials().getPassword().equals(dest.getSmbFile().getContext().getCredentials().getPassword())
                    ) {

SmbFile adjusteddest = new SmbFile(dest.getURL(), src.getContext());
src.renameTo(adjusteddest);
...
} else {
     src.copyTo(dest);
     src.delete();
     ...
}

I need to account for moving a file from

ShareA to ShareA
ShareB to ShareB
ShareA to ShareB
ShareB to ShareA

Is there a better way to tell if the context of src and the context of dest are both for the same share?  I feel the first if statement above is a hack but it seems to work.

**Comment by mbechler** [comment]
You should be able to compare the credential object directly using equals, but otherwise I guess this would be the way to go.

**Comment by AntoonNaegels** [comment]
@rconoverq I experienced similar issues. with jcifs-ng:2.1.3
Replacing the rename with copy/delete resolved the issue: 

src.copyTo(dest); + 
src.delete();
