### ISSUE TITLE
SMB3 Encryption

### ISSUE THREAD

**Issue by Sentaroh** [AgNO3/jcifs-ng#182]
Does SMB3 encryption support? 
If you don't, do you plan to support it?

**Comment by mbechler** [comment]
Not yet. I was and am planning to, and even started working on it quite a while back but haven't gotten around working more on it for a really long time.

**Comment by Sentaroh** [comment]
Thanks.

**Comment by helmutat** [comment]
> Not yet. I was and am planning to, and even started working on it quite a while back but haven't gotten around working more on it for a really long time.

I know that is an old question, but still valid. Is there any new status for Encryption Availibility?

Thanks!

**Comment by mbechler** [comment]
Unfortunately, no progess so far.

**Comment by jbostoen** [comment]
Also interested in this. Any new update, please?
