### ISSUE TITLE
Exception during access to Freebox server (SMB V1)

### ISSUE THREAD

**Issue by emarch06** [AgNO3/jcifs-ng#193]
Hi,

I've got an exception accessing a samba share
The share is on a freebox server (mini), which is based on smb V1 I think.

I used this simple java test program:
https://gist.github.com/courville/a0e6fe1ce2f31c9adc52191216eed3e0
I used jcifs-ng 2.1.3.

Pcap file is here:
[smb_freebox.zip](https://github.com/AgNO3/jcifs-ng/files/3837908/smb_freebox.zip)
The server name is "serveur" and its IP is 192.168.0.254
The computer that runs the client has IP  192.168.0.44

Exception is:
jcifs.smb.SmbException: Invalid operation for IPC service: Trans2FindFirst2[command=SMB_COM_TRANSACTION2,received=false,errorCode=0,flags=0x0018,flags2=0x0000,signSeq=0,tid=1,pid=2823,uid=0,mid=0,wordCount=0,byteCount=0,totalParameterCount=0,totalDataCount=0,maxParameterCount=10,maxDataCount=65535,maxSetupCount=0,flags=0x00,timeout=0,parameterCount=0,parameterOffset=0,parameterDisplacement=0,dataCount=0,dataOffset=0,dataDisplacement=0,setupCount=1,pad=0,pad1=0,searchAttributes=0x16,searchCount=200,flags=0x00,informationLevel=0x104,searchStorageType=0,filename=\]
        at jcifs.smb.SmbTreeImpl.checkRequest(SmbTreeImpl.java:519)
        at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:449)
        at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
        at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
        at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
        at jcifs.smb.DirFileEntryEnumIterator1.open(DirFileEntryEnumIterator1.java:67)
        at jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67)
        at jcifs.smb.DirFileEntryEnumIterator1.<init>(DirFileEntryEnumIterator1.java:46)
        at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:225)
        at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
        at jcifs.smb.SmbFile.listFiles(SmbFile.java:1199)
        at smbcli.main(smbcli.java:137)

Full log is here:
[smb_freebox.log](https://github.com/AgNO3/jcifs-ng/files/3837930/smb_freebox.log)

Do you have any idea of the issue?
Thanks and regards
Eric

**Comment by mbechler** [comment]
As far as I can tell the code is actually trying to list files on the IPC share. This is likely not going to work and there is a check in place to prevent doing that. I may have misunderstood the original code's intention or the orignal code was buggy but that check has been there with the original jcifs as well.

**Comment by courville** [comment]
To provide more context on how to reproduce on any SMBv1 server, the error occurs when top level is non password protected and there is at least one share served that is password protected.
I believe it is also related to https://github.com/AgNO3/jcifs-ng/issues/141
I have reproduced here on another server too.

**Comment by emarch06** [comment]
Hi,
I'm browsing this share \\serveur\freebox
It's the root level of the share.
There's only one share on the server
There's no password on the share.
I enabled SMB V1 support on windows 10 with optionalfeatures command

Basically, I do those steps:
smbFile = new SmbFile(args[1], ctx); where args[1] is smb://serveur/freebox/
smbFile.getType(); returns SmbFile.TYPE_SHARE
smbFile.getName(); returns freebox/
Then I call smbFile.listFiles();
Then I catch the exception.

I don't implicitly ask to list IPC$ special folder, I think the listFiles method does this and gets the error.
But I don't get what fails ;-)
Any idea?

**Comment by courville** [comment]
The only thing we saw that perhaps could lead to this behavior is that in SmbSessionImpl getSmbTree, if share is null, share is set to IPC$

**Comment by mbechler** [comment]
I think I managed to find the issue, when retrying with anonymous auth after the guest authentication failed the share was set to null. Please try with master.

**Comment by emarch06** [comment]
Hi,

I made a build of the sample app with the master branch.
I confirm the issue is fixed :)
You can merge the patch.

Thanks for your help and regards
Eric

**Comment by courville** [comment]
I guess that issue can be closed.
