### ISSUE TITLE
Is smb3.1 officially supported?

### ISSUE THREAD

**Issue by yukiato** [AgNO3/jcifs-ng#198]
I am always indebted.
Customer application uses smb2 with jcifs-ng, WAN speed does not come out.
I want to use smb3.1 for Windows 2016 Server.
Is smb3.1 officially supported?

**Comment by mbechler** [comment]
The smb 3.1 core is supported, so you can connect to a server using that protocol level (by default it's not enabled at this point). However, none of the protocol extensions are implemented at this point.

Also, I wouldn't expect much performance gain from SMB3 features, I suppose the most limiting thing we lack right now is multi-credit support (from SMB2.1).
