### ISSUE TITLE
Support for Android?

### ISSUE THREAD

**Issue by ma99us** [AgNO3/jcifs-ng#20]
It seems that jcifs-ng does not work on Android. I see exceptions like this:
java.lang.ClassNotFoundException: org.ietf.jgss.Oid
That is because Oid class does not seem to be a part of Android jre.
Legacy jcifs is working fine on Android, btw.
Is there a way to make jcifs-ng more portable, or include Oid-related classes into Android lib?

**Comment by mbechler** [comment]
I think you might be able to bundle some of the code from https://github.com/cconlon/kerberos-android-ndk/tree/master/src/org/ietf/jgss to get the classes used in the APIs. Obviously, you won't be able to use kerberos authentication without an actual JGSS implementation (as far as I can tell there is one provided by the same project, but I haven't really looked at it in detail) but NTLM should work just fine.

Changing some APIs we would be able to remove the dependency on those classes as long as kerberos is not actually used, but that would be something for a new major version.

**Comment by ma99us** [comment]
Ok, I was looking into that project and it seems to have lots of dependencies on other classes from  edu.mit.* packages. I was wondering if maybe it is easier to remove Oid from jcifs-ng itself and replace it with some custom implementation. One way or another, it would be good to make jcifs-ng Android-friendly again. If I manage to hack it to work, I will let you know.
Thanks.

**Comment by mbechler** [comment]
Right, I missed that this was also the case for Oid. Bouncycastle's ASN1ObjectIdentifier should be a suitable replacement for Oid as it is used.

**Comment by mbechler** [comment]
I pushed a patch to the android branch that removes the JGSS dependency if kerberos auth is not used.

**Comment by ma99us** [comment]
Sweet, thanks. I will check it out.

**Comment by ma99us** [comment]
Ok, thanks. I can now run it on Android.
The only problem I have noticed is that I can not explore Workgroup root directory and see other hosts with shares. With legacy jcifs lib I was able to connect to "smb://" and list all hosts. With jcifs-ng i get "Failed to connect to server" exception. Once I provide full hostname as "smb://host/", then I can connect fine. How do I list hosts in the root of Network? 
BTW: I had to comment out this check in SmbSessionImpl:
//                     if ( response.isLoggedInAsGuest() && !this.credentials.isGuest() ) {
//                        throw new SmbAuthException(NtStatus.NT_STATUS_LOGON_FAILURE);
//                    }
otherwise Ananonimus connection would not work. Since response still thinks its logged in as Guet if username is null.

**Comment by mbechler** [comment]
I will look into the host enumeration, seems like I broke that when fixing the address failover behavior.

Regarding the guest logon, what kind of server setup do you have there? Unfortunately the guest logon specifics do not seem to be properly documented anywhere - but as far as I understood it so far, loggedInAsGuest should not be set when anonymous auth was requested by the client.

Replacing !this.credentials.isGuest() with !anonymous will probably fix the issue.

**Comment by mbechler** [comment]
See #22 for my research into server enumeration.

**Comment by mbechler** [comment]
JGSS API changes are scheduled for 2.1

**Comment by ma99us** [comment]
Thanks for your support. At this point, the only thing which bugs me is a confusion with broken server enumeration. Can legacy SMB1 enumeration be fixed?

**Comment by Jomme5** [comment]
Same problem here. What is that patch?

**Comment by SteveGreatApe** [comment]
Hi, I'm using the latest 2.1.0 Snapshot on Android with no problems.

Server enumeration works if you use a CIFSContext with SMB2 disabled for reading the root and Workgroups.

Once you've enumerated the servers you need to re-create the SmbFile objects referring to them using a CIFSContext with SMB2 enabled. You can then browse down into the contents of the servers.

**Comment by Jomme5** [comment]
Ok. How do you get this snapshot in Android Studio?

**Comment by SteveGreatApe** [comment]
I've built my own copy from the source here, then just manually copied it into my Android project, these are the dependencies I'm using.

```
dependencies {
    implementation files('libs/jcifs-ng-2.1.0-SNAPSHOT.jar')
    implementation 'org.slf4j:slf4j-api:1.7.25'
    implementation "org.bouncycastle:bcprov-jdk15on:1.56"

```

**Comment by Jomme5** [comment]
Do you do this with gradle? I have no idea where to start. Normally, I just add them in build.gradle. I've download the zip-project, but I'm stuck on how to build that project.

**Comment by SteveGreatApe** [comment]
To build jcifs-ng you need to have maven installed. Then in the top folder type:

`mvn package`

If it's all worked you should find jcifs-ng-2.1.0-SNAPSHOT.jar in the target folder.

**Comment by Jomme5** [comment]
Life can be simple sometimes. Thx

**Comment by SteveGreatApe** [comment]
I've pushed an update to my BufferedMediaDataSource project to show jcifs-ng in action on Android.

https://github.com/SteveGreatApe/BufferedMediaDataSource

The project is an implementation of the Android MediaDataSource API for playing Videos over the network, or other streamed sources.

The Demo App uses jcifs-ng to browse the network to select a video to play, hopefully it'll show you all need to know to get your code working.

**Comment by travisjayday** [comment]
My server requires Kerberos authentication... Is there any way to get around it on Android? Even though it's not part of the jre?

**Comment by mbechler** [comment]
You could try to pull the GSS implementation from OpenJDK, but that's likely not going to be much fun. 
An alternative option may be using Apache Kerby, but I've never had a closer look and that likely requires some porting.
