### ISSUE TITLE
Access denied with Windows 10 and required from client SPN

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#203]
Hi,
We are hitting an access denied with  SMB2_SESSION_SETUP when trying to connect to Windows 10 environment.
The error code from trace is: NT_STATUS_ACCESS_DENIED = 0xC0000022
We found out from the Event Viewer on the smb server complains about SPN:
_______________________________
Status: {Access Denied}
A process has requested access to an object, but has not been granted those access rights. (0xC0000022)
SPN: 
SPN Validation Policy: SPN required / validate full
_______________________________

Does jcifs-ng supports Service Principal Names ?  Or is there a workaround for it?

Thanks for the supports you have been providing!

**Comment by mbechler** [comment]
I didn't find any detailed technical documentation on what this flags does, but my best guess would be that this means checking the MsvAvTargetName provided in NTLM authentication against expected values. 

While there is already generic support for the attribute in the NTLM implementation, it is not currently set during SMB session setup. I wasn't aware that anyone was actually checking that, so I didn't bother to. I'll look into that.

**Comment by mbechler** [comment]
Please check whether the patch allows you to connect.

**Comment by thanh-vn** [comment]
Yes, the patch allows us to connect to Windows 10 with 'SPN required from client' option.
Thank you for pretty quick support of this issue!
