### ISSUE TITLE
Supported SMB3 Features 

### ISSUE THREAD

**Issue by felixRajkumar** [AgNO3/jcifs-ng#206]
Hi,
   I would like to read a file using SMB3 on remote server. May I know the SMB3 features supported by jcifs-ng 2.1.3.Thanks in advance!

**Comment by mbechler** [comment]
Right now, none except the negotiation (with preauth integrity). What features are you interested in? I've been wanting to implement encryption for quite a while now, but that is the only SMB3 feature I had planned.

**Comment by felixRajkumar** [comment]
> Right now, none except the negotiation (with preauth integrity). What features are you interested in? I've been wanting to implement encryption for quite a while now, but that is the only SMB3 feature I had planned.

Same here, I too wish for the Encryption Implementation along with the Multi Channel support.
