### ISSUE TITLE
sometimes OOM if setting jcifs.smb.client.maxVersion=SMB311

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#215]
I got OOM issue when setting jcifs.smb.client.maxVersion=SMB311 for talking to smb server (Windows server 2008 R2) does not support SMB3.  My settings are:
jcifs.smb.client.minVersion=SMB202
jcifs.smb.client.maxVersion=SMB311

Here is the error stack
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
Exception in thread "Transport29" java.lang.OutOfMemoryError: Java heap space
        at jcifs.smb.SmbTransportImpl.negotiate2(SmbTransportImpl.java:655)
        at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:535)
        at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:707)
        at jcifs.util.transport.Transport.run(Transport.java:732)
        at java.lang.Thread.run(Thread.java:811)

I see that the respLen pickups value inconsistently.  Sometimes it is 172 (I think this is correct value); sometimes it is a large number,  ex: 2052194305.  So when the jcifs.smb.client.maxVersion is set to SMB311, it tries the code below and OOM happens.

            if ( doPreauth ) {
                negoRespBuffer = new byte[respLen];
                System.arraycopy(this.sbuf, 4, negoRespBuffer, 0, respLen);
            }

Could you take a look when you have time?
Thanks,

**Comment by mbechler** [comment]
This should be fixed with cea6a08921d584ca9ea5b7149807402a0519ebc7

**Comment by thanh-vn** [comment]
Picked up the commit https://github.com/AgNO3/jcifs-ng/commit/cea6a08921d584ca9ea5b7149807402a0519ebc7 and problem is fixed.  Close the issue.
Thanks much!
