### ISSUE TITLE
Android 9 support as Deprecation of Bouncy Castle ciphers

### ISSUE THREAD

**Issue by ashishsoni4u** [AgNO3/jcifs-ng#217]
I am trying to connect to network share hosted in Windows server 2019, i am getting error that Failed resolution of: Lorg/bouncycastle/asn1/ASN1ObjectIdentifier;", java.lang.ClassNotFoundException: Didn't find class "org.bouncycastle.asn1.ASN1ObjectIdentifier" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", /system/lib]]. 
While going through the anroid 9.0 migration guide i found that "Android 9 deprecates several ciphers from the Bouncy Castle provider in favor of those provided by the Conscrypt provider. Calls to getInstance() that request the Bouncy Castle provider generate NoSuchAlgorithmException errors. To resolve the errors, do not specify a provider in getInstance() (that is, request the default implementation)."

Any plan to support android 9.0

**Comment by mbechler** [comment]
You are missing a compatible bouncycastle version on your classpath. Maybe some android versions have provided a bundled bouncycastle, so you did not notice. Bouncycastle however is and is going to aways be a dependency, so you will have to include that in you application.
