### ISSUE TITLE
SmbFileInputStream param sharing not used

### ISSUE THREAD

**Issue by alb-i986** [AgNO3/jcifs-ng#222]
Hi,
While inspecting the code to have a clue on how to use this API, I noticed an issue with SmbFile#openInputStream.

Its param `sharing` is not actually used in the callee below: see [here](https://github.com/AgNO3/jcifs-ng/blob/59c3c0a89f541966f38dc50dd43d5e2a315e4fa3/src/main/java/jcifs/smb/SmbFileInputStream.java#L90).

Thanks

**Comment by mbechler** [comment]
Good catch.
