### ISSUE TITLE
SMB v3

### ISSUE THREAD

**Issue by eseanucristian** [AgNO3/jcifs-ng#228]
Hi,
The 2.x series will be discountinued. Will it be a 3,x series ? What SMB v3 features it will support ?

Thanks.
Cristian

**Comment by mbechler** [comment]
2.0 is discontinued. There already is basic smb3.* support in 2.1, however none of the real features are currently impelmented. Encryption would be the first on the feature wishlist. Not sure whether implementing anything else is feasible in the medium term.
