### ISSUE TITLE
Jcifs-ng examples

### ISSUE THREAD

**Issue by manasBelekar** [AgNO3/jcifs-ng#23]
Hi,

I want leverage SMB2/3 files sharing capabilities and integrate it in my project.
I have built the jcifs-ng in my local environment. But I couldn't find any examples or sample code which could be used as reference. Could you please rpovide sample/ example codefor reference

thanks
Manas

**Comment by manasBelekar** [comment]
Here i particularly want to use only SMB3/ 2 and no smb1.

**Comment by mbechler** [comment]
There isn't any proper example code (yet). General usage is centered around the jcifs.smb.SmbFile class/SmbResource interface, these also have javadocs describing the available operations. You can also have a look at the test cases included, many of these should serve nicely as usage examples.

With regards to enforced SMB2+ operation all you really need to do is set the system property (this can also be configured programatically) jcifs.smb.client.disableSMB1=true (or, if you just want allow fallback to SMB1 if unavailable use jcifs.smb.client.enableSMB2=true).

**Comment by manasBelekar** [comment]
HI @mbechler,

Could you please let me know, does jcifs-ng supports ssl? I need this confirmation before proceeding.

Thanks,
Manas

**Comment by mbechler** [comment]
There is no SSL in SMB. If you are talking about SMB encryption, then the answer is: not yet. Current master (going to be 2.1) already includes experimental SMB3 support (which is a prerequestite for encryption) and I have in fact been working on encryption support, but it does not work yet and I'm not sure whether to include it in 2.1 or not.

**Comment by manasBelekar** [comment]
Thanks.
Also, Can i use this library for communicating over SSH. Is that supported in JCIFS Ng?

**Comment by mbechler** [comment]
? Can you elaborate on what exactly you are trying to achieve?

**Comment by manasBelekar** [comment]
I want to use smb capabilities for communicating over SSH (Linux m/c). Can I use it thr=ough the library?

**Comment by mbechler** [comment]
Well, I guess you can set up an external SSH tunnel, but other than that, no.

**Comment by manasBelekar** [comment]
ok. Thanks a lot
