### ISSUE TITLE
jcifs.smb.SmbException: 0xC0000466

### ISSUE THREAD

**Issue by dennislixin** [AgNO3/jcifs-ng#232]
I found the error 0xC0000466 when trying to connect the customer's ONTAP 8.2 server.
What does this error mean? Any idea how to fix it?

Please let me know if you need more information.

jcifs-ng version: jcifs-ng-2.1.4

jcifs.properties file setting:
> jcifs.smb.client.minVersion = SMB1
> jcifs.smb.client.maxVersion = SMB311
> jcifs.traceResources = true
> jcifs.smb.client.ipcSigningEnforced = false
> jcifs.resolveOrder = LMHOSTS,WINS,DNS,BCAST
> jcifs.smb.client.dfs.disabled = true
> jcifs.smb.client.forceUnicode = true

Error stack:
> jcifs.smb.SmbException: 0xC0000466
> jcifs.smb.SmbException: 0xC0000466
> 	at jcifs.smb.SmbTransportImpl.checkStatus2(SmbTransportImpl.java:1461)
> 	at jcifs.smb.SmbTransportImpl.checkStatus(SmbTransportImpl.java:1572)
> 	at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1027)
> 	at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1543)
> 	at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:549)
> 	at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369)
> 	at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347)
> 	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611)
> 	at jcifs.smb.SmbTreeImpl.connectLogon(SmbTreeImpl.java:785)
> 	at jcifs.smb.SmbTransportPoolImpl.logon(SmbTransportPoolImpl.java:350)
> 	at jcifs.smb.SmbTransportPoolImpl.logon(SmbTransportPoolImpl.java:340)
>

**Comment by mbechler** [comment]
I don't think I have seen this error before. This seems to be a bit unspecific one and seems to either indicate an error with the authentication backend of the server or maybe some SPNEGO related issue. Maybe you can get some more information in the filer logs?

**Comment by dennislixin** [comment]
Thanks for the reply. I will ask the customer to check the filter log.

**Comment by dennislixin** [comment]
@mbechler The client checked the security trace, but could not find anything.
Any idea on what filter log to check?

**Comment by mbechler** [comment]
Unfortunately, no, I don't have much experience with netapps.

**Comment by dennislixin** [comment]
This issue is more likely to be ONTAP 8.2 bug. 
I am closing this issue.
Thanks for your help.

**Comment by dennislixin** [comment]
This issue is more likely to be ONTAP 8.2 bug. 
Thanks for your help.
