### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by olcha** [AgNO3/jcifs-ng#236]
Hi, jcifs-ng support IPv6? 
I must choose library for transfer files between shared folder and local, which can working in IPv6 network.

**Comment by mbechler** [comment]
I don't think there should be anything stopping you from using IPv6. Some legacy stuff cant't work (think Netbios name resolution), but this is not required for accessing a share.

But I have to admit I never really tested this so far, I should probably add a IPv6 setup to my test suite.

**Comment by olcha** [comment]
Thanks, I check connection through IPv6 - all working!
