### ISSUE TITLE
Maven repo seems to be out of date

### ISSUE THREAD

**Issue by casolorz** [AgNO3/jcifs-ng#25]
Is this the correct maven package? https://mvnrepository.com/artifact/eu.agno3.jcifs/jcifs-ng
It appears to be out of date. 

Thanks.

**Comment by mbechler** [comment]
Yes, it is. 2.1 is not yet released.

**Comment by casolorz** [comment]
I see, thanks for the info. Just to be sure, 2.1 is the one that works with Android, right?

**Comment by mbechler** [comment]
Yes, making that possible required some API changes so that had to go in the major release.

**Comment by casolorz** [comment]
Yeap just got it running by building the jar. Still having some issues but that is just probably from me not understanding the api. While building the jar with `mvn install` I had to comment out the `maven-gpg-plugin`, is that normal or did I mess something up?

**Comment by mbechler** [comment]
I guess that is normal if you install it, -Dgpg.skip=true might also work.

**Comment by casolorz** [comment]
Ok, thanks.
