### ISSUE TITLE
Need advice for Type3Message construction

### ISSUE THREAD

**Issue by MANOJ-SREERAMA** [AgNO3/jcifs-ng#255]
I need to do NTLM authentication over LDAP protocol. For this I am trying to use UnboundID and jcifs-ng together. ([Courtesy](https://sourceforge.net/projects/javaldapntlmbind/)). Everything works fine using the code attached if domain controllers doesn't require LDAP signing (integrity check). If [LDAP signing](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/enable-ldap-signing-in-windows-server) is enabled, code fails with message 

> The server requires binds to turn on integrity checking if SSL\TLS are not already active on the connection

If I use NtlmFlags.NTLMSSP_NEGOTIATE_SIGN  flag for Type3Message, code fails with following message ( even if we disable LDAP Signing in domain controller )

> resultCode :: 49 (invalid credentials)
> resultCode :: 80090302: LdapErr: DSID-0C090588, comment: AcceptSecurityContext error, data 1, v2580

I have checked the construction of Type3Message in NTLMContext and followed similar approach with no luck. Please let me the correct way to do it or JCIFS-NG itself supports it in another way. Thanks in advance.

Attached the code for reference. 
[NtlmBindRequest.txt](https://github.com/AgNO3/jcifs-ng/files/5494878/NtlmBindRequest.txt)

**Comment by mbechler** [comment]
You should be able to provide the flags like you do (modulo some flags that are added automatically). I would suggest you compare the resulting flag negotation with the one of a working client.

Also, I would assume there is some QOP negotation going on in the SASL exchange as well and only setting this in the NTLM message is not sufficient (the signing flag is primarily for validation purposes).
