### ISSUE TITLE
failed to connect to localhost with stunnel configuration

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#265]
I have a user of my android app reporting that transitioning to jcifs-ng, he cannot connect to his server using an stunnel configuration forwarding 127.0.0.1:445 port to remote SMB server on same port via stunnel.
I am able to replicate the setup and confirm that jcifs-old works while I get a `Failed to connect: 0.0.0.0<00>/127.0.0.1 ECONNREFUSED` with jcifs-ng.
Debug logs can be found here: [org.courville.nova.zip](https://github.com/AgNO3/jcifs-ng/files/5791214/org.courville.nova.zip)

**Comment by mbechler** [comment]
```
12:03:12.587 [AsyncTask #1] DEBUG c.a.filecorelibrary.jcifs.JcifsUtils - getSmbFile: for smb://127.0.0.1:1445/
12:03:12.588 [AsyncTask #1] DEBUG c.a.filecorelibrary.jcifs.JcifsUtils - isSMBv2Enabled=true
12:03:12.588 [AsyncTask #1] DEBUG c.a.filecorelibrary.jcifs.JcifsUtils - isServerSmbV2 for 127.0.0.1 previous state is null
12:03:12.589 [AsyncTask #1] DEBUG c.a.filecorelibrary.jcifs.JcifsUtils - isServerSmbV2: probing smb://127.0.0.1/ to check if smbV2
```

This looks like the port actually is 1445 but your probing code is connecting to smb://127.0.0.1/ (without the port). Any chance this is causing the problem? Otherwise, it's still likely an issue with the non-standard port that I would have to look into

**Comment by courville** [comment]
Indeed this one is on my side and thanks for pointing me in the right direction.
