### ISSUE TITLE
SmbException on smbFile.listFiles() happening sometimes

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#267]
In my Android application when listing servers, a probing of their capabilities is done and on my synology (DS720P) set to support SMB2 only, during the first probing, `smbFile.listFiles()` fails systematically but not afterwards.
I captured the attached TRACE logs with `jcifs.netbios.NameServiceClientImpl`, `jcifs.smb.SmbSessionImpl` and `jcifs.smb.SmbTransportImpl`.

Following config is used for SMB2 probing:
```
prop.put("jcifs.smb.client.disableSMB1", "true");
prop.put("jcifs.smb.client.enableSMB2", "true");
prop.put("jcifs.smb.client.useSMB2Negotiation", "true");
prop.put("jcifs.smb.client.dfs.disabled", "true");
prop.put("jcifs.smb.client.ipcSigningEnforced", "false");
prop.put("jcifs.smb.client.disablePlainTextPasswords", "false");
```

Logs: [org.courville.nova-probe-smbexcept-smbv2.zip](https://github.com/AgNO3/jcifs-ng/files/5868483/org.courville.nova-probe-smbexcept-smbv2.zip)

**Comment by mbechler** [comment]
This looks like the same issue as in #268.

**Comment by courville** [comment]
Thus closing this issue as duplicate.
