### ISSUE TITLE
slow browsing when using BCAST,DNS resolver order but not with DNS,BCAST one on Swisscom gateway

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#269]
In my Android application in front of a Swisscom SMB enabled router, I experience slow browsing when using BCAST,DNS resolver order but not with DNS,BCAST where everything is fine. The router is named INTERNETBOX-NAS, I see that it fails to resolve via BCAST and I have traces of attempts to check if DS720P SMB share exists (which is not since I am not in the same LAN).

I captured the attached logs with TRACE enabled for `jcifs.netbios.NameServiceClientImpl`, `jcifs.smb.SmbSessionImpl` and `jcifs.smb.SmbTransportImpl`.

Following config is used during the test:

prop.put("jcifs.smb.client.disableSMB1", "true");
prop.put("jcifs.smb.client.enableSMB2", "true");
prop.put("jcifs.smb.client.useSMB2Negotiation", "true");
prop.put("jcifs.smb.client.dfs.disabled", "true");
prop.put("jcifs.smb.client.ipcSigningEnforced", "false");
prop.put("jcifs.smb.client.disablePlainTextPasswords", "false");

Logs:

- BCAST,DNS resolver order resulting in slow browsing (but working): [org.courville.nova-BCASTDNS-slow-SWC.zip](https://github.com/AgNO3/jcifs-ng/files/5878158/org.courville.nova-BCASTDNS-slow-SWC.zip)
- DNS,BCAST resolver order resulting in a fast normal experience: [org.courville.nova-DNSBCAST-fast-SWC.zip](https://github.com/AgNO3/jcifs-ng/files/5878159/org.courville.nova-DNSBCAST-fast-SWC.zip)

Side note it means that the "easy fix" of adopting BCAST,DNS order to get around https://github.com/AgNO3/jcifs-ng/issues/268 is not universal resulting for now in an awkward setting letting users specify the resolver order which is not very average Joe compatible.

**Comment by mbechler** [comment]
I don't think the lookup of DS720P could be initiated by the library, any clue where this is coming from?
As mentioned before, BCAST before DNS lookup can be expected to perform pretty bad. If no one is answering BCAST will have to wait for a timeout.

**Comment by courville** [comment]
The DS720P lookup comes from my android application that remembers registers servers and try to check if they are alive to display these SMB servers. Current logs are taken on another network and I understand that with BCAST first it will take a long time to answer the DS720P lookup.

However, what I do not understand is why it should affect the INTERNETBOX-NAS browsing.

To avoid interference in the logs, I will reset my application and takes fresh logs without DS720P.

I got your point and will set up DNS,BCAST as default resolver order in my application anyway.

My application is targeted more for non enterprise world, in my mind, and since there is a very few people setting their LAN network with DNS entries for their NAS appliances, it led me to the BCAST,DNS resolver order in the past.

**Comment by courville** [comment]
DNS,BCAST order is the solution. Let's declare this issue closed. Will reopen if need be. Thank you a lot for the continuous dedicated support.
