### ISSUE TITLE
 jcifs.RuntimeCIFSException: jcifs-ng requires Java 1.7 or above. You are running 0.0

### ISSUE THREAD

**Issue by casolorz** [AgNO3/jcifs-ng#27]
When registering the URL handler on Android I get that error. 

```
at jcifs.context.SingletonContext.registerSmbURLHandler(SingletonContext.java:125)
at jcifs.Config.registerSmbURLHandler(Config.java:70)
```

Seems like Android is missing `Runtime.class.getPackage().getSpecificationVersion()`

Not sure what the right solution is since I don't know what the requirements are for custom url handlers.

**Comment by mbechler** [comment]
On first glance it looks like custom URL handlers are supported by android, but I don't find any information whether that is version specific. But I guess I'm okay with just adding an exception for android like.

**Comment by mbechler** [comment]
So I guess this is working in master, right? If not, please reopen.

**Comment by casolorz** [comment]
This still failed for me. Mine has http://www.android.com/ with a / at the end. I don't know if that applies to all versions, so maybe check against startsWith or contains.

**Comment by casolorz** [comment]
Just FYI, doing a java.vendor.url check as to whether it contains android.com is working for me. 

That being said, I don't know what parts of Java 7 are required for this to work, and whether they are present on all Android versions. If I see a crash on older versions I'll report.

**Comment by mbechler** [comment]
Now checking prefix.
