### ISSUE TITLE
169.254.x.x address resolved by BCAST resolver for one user

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#270]
One user of my Android application is reporting (https://github.com/nova-video-player/aos-AVP/issues/416) failure to connect to one of his WDMyCloud NAS (WDMYCLOUD).
Looking a the following TRACE logs: [spiderdaz-test15-bcast_dns-cleaned.zip](https://github.com/AgNO3/jcifs-ng/files/5879751/spiderdaz-test15-bcast_dns-cleaned.zip) it appears that the BCAST resolver kicks in and surpisingly reports 169.254.7.23.:
```
21:26:50.042 [Thread-9] DEBUG jcifs.netbios.NameServiceClientImpl - Resolved 'WDMYCLOUD' to addrs [WDMYCLOUD<20>/169.254.7.23] via RESOLVER_BCAST
```
Note that the resolver order is BCAST,DNS and that other application can connect to the NAS correctly.

**Comment by mbechler** [comment]
169.254.X.X are IPv4 autoconfiguration addresses, so it seems likely that the system answering actually "believes" that this is it's address, therefore the BCAST/Netbios name lookup will give wrong results. It would be interesting to investigate what logic the other systems, that can connect, resolve the system address.

**Comment by courville** [comment]
Thank you for your answer. Since I do not have access to this user setup, I will unfortunately not be able to follow through on the investigation and check what the other apps (vlc or file browsers) are doing in this respect.

I thus propose to close the issue and reopen if I get more noise about it and can reproduce myself.
