### ISSUE TITLE
access to Windows 10 not working

### ISSUE THREAD

**Issue by rpolzer** [AgNO3/jcifs-ng#278]
- device A running Windows 10 with user A with password, having shares open for access by everybody without credentials
- device B running Windows 10 with user B without password, having shares open for access by everybody without credentials
- device C running Android and using jcifs-ng 2.1.5

A and B can use the shares of each other without credentials.
C can use the shares of A only when entering username and password.
C cannot use the shares of B, jcifs asks always for credentials.
I have tried the following combinations, all of them fail:
- username + no password
- username + wrong password
- guest + no password
- guest + wrong password

Before using jcifs-ng 2.1.5, I used jcifs 1.3.19, which allowed C to use the shares of B without credentials.

**Comment by mbechler** [comment]
jcifs-ng no longer does permit automatic fallback to guest authentication (which is a special authentication mode in SMB), you would have to request that using the withGuestCredentials(). Have you tried that?

**Comment by rpolzer** [comment]
Thank you for this hint! Now it works as expected:
```
Properties p = new Properties();
p.put("jcifs.smb.client.ipcSigningEnforced", "false");
p.put("jcifs.smb.client.useExtendedSecurity", "false");
CIFSContext c = new BaseContext(new PropertyConfiguration(p)).withGuestCrendentials();
```
