### ISSUE TITLE
Request for release containing newer bcprov compatibility fix

### ISSUE THREAD

**Issue by dschlenk** [AgNO3/jcifs-ng#284]
I'm working on a patch to get `bcprov`, `jcifs-ng`, `j-interop-ng` updated in [OpenNMS](https://github.com/OpenNMS/opennms). Would really appreciate a release that contains the `ASN1OutputStream` fix in 5f4ece7. Anything I can do to assist?

**Comment by mbechler** [comment]
As chance would have it I'm currently preparing a release. Sorry it took so long.

**Comment by dschlenk** [comment]
Thank you!! No worries!
