### ISSUE TITLE
listFiles() is extremely slow under certain conditions

### ISSUE THREAD

**Issue by rpolzer** [AgNO3/jcifs-ng#290]
With the following code, listFiles() is extremely slow only when running on Android and only when reading from a device that needs credentials. The same code is fast when running on Linux or when acessing devices not asking for credentials.

Any Idea?

try {
    jcifs.Config.registerSmbURLHandler();
    Properties p = new Properties();
    p.put("jcifs.smb.client.ipcSigningEnforced", "false");
    p.put("jcifs.smb.client.useExtendedSecurity", "false");
    cifsc = new BaseContext(new PropertyConfiguration(p)).withGuestCrendentials();
    smbFolder = new SmbFile("smb://device/folder", cifsc);

    smbList = smbFolder.listFiles(); // extremely slow on Android when reading from devices that need credentials

} catch (SmbAuthException ae) {
    // ask for credentials

**Comment by mbechler** [comment]
If it's really authenticated/non authenticated that makes the difference and signing is still negotiated, that crypto could be slow(er) on Android. But I can't imagine this making such a noticable difference. Can you get a log file so that we can check what actually  takes so long?

**Comment by rpolzer** [comment]
please tell me how to produce a log file

**Comment by mbechler** [comment]
That depends on the logger implementation you are using (log4j,logback,...), check which slf4j backend you use and refer to its documentation. A good start would be a TRACE level log for *jcifs.smb.SmbTransportImpl*

**Comment by rpolzer** [comment]
I did logging at trace level on both operating systems, but - this is strange - I cannot reproduce the long waiting time seen several times before.

So I close this issue, sorry.
