### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by casolorz** [AgNO3/jcifs-ng#30]
I have released an alpha version of my Android app with this library and I got this report on Crashlytics. No idea how to reproduce. 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at jcifs.smb.SmbResourceLocatorImpl.getType(SmbResourceLocatorImpl.java:414)
       at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:207)
       at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:277)
       at jcifs.smb.SmbFile.listFiles(SmbFile.java:1177)
```

**Comment by mbechler** [comment]
I am assuming this is the current master version running?

Looking through the code I guess that could possibly happen for some kinds of invalid or "empty" URLs. I don't suppose you are able to find out what URL caused that?

May take me a while to get to it, but I will try to reproduce this.

**Comment by casolorz** [comment]
Yes, current master, or as of a week ago. 

This was just an  automatic report so no way to reproduce it on my end.

**Comment by mbechler** [comment]
My tests suggest that this was caused by supplying an invalid/unsupported URL like smb:foo. This should now result in a more meaningful error.
