### ISSUE TITLE
Question - Is SMB3 fully supported now?

### ISSUE THREAD

**Issue by GregBragg** [AgNO3/jcifs-ng#300]
Hi,

Just want to know what the progress is on SMB3 support, because the last comment I read in the Issue log was back from around 2020, so has any progress been made since then?

I understand we can connect to an SMB3 share, however can jcifs-ng read a file off a directory successfully for download? (Sorry I haven't tried yet...)

Thanks.

**Comment by mbechler** [comment]
Unfortunately I have still not made any further progress regarding SMB3 features.

However, as long as SMB encryption is not enabled (which is not the default) the basic operations should work just fine.
None of the other features should be show stoppers, symbolic links - if used - may cause some issues, but I suppose everything else could be considered optional extensions.

**Comment by GregBragg** [comment]
Thanks! I appreciate your time to answer my question. Best regards...

**Comment by GregBragg** [comment]
Questions answered... Thanks!

**Comment by kimmerin** [comment]
FWIW: Windows 2019 and later uses SMB3 encryption by default, so

> as long as SMB encryption is not enabled (which is not the default)

is no longer the case

**Comment by GregBragg** [comment]
> FWIW: Windows 2019 and later uses SMB3 encryption by default, so
> 
> > as long as SMB encryption is not enabled (which is not the default)
> 
> is no longer the case

I have to get my Infrastructure team to turn it off for an Azure Files share (if that is even possible) if they want to use that as a solution to migrate from an old on-prem file server to a cloud based solution, otherwise I will be using the Azure SDK for Java instead. There are also other alternatives that we are exploring...

ATM I'm looking to upgrade our code to use SMB3 first, as it is an easy quick win, rather than a whole scale refactor of our integration code.

Thanks muchly for the feedback...

**Comment by JustMyGithub** [comment]
Not sure whether this is useful, but according to https://github.com/hierynomus/smbj/issues/708 https://github.com/hierynomus/smbj has a Java implementation of SMB3 encryption. smbj is pointed to by the original jCIFS website.
