### ISSUE TITLE
Project Release Schedule

### ISSUE THREAD

**Issue by eg-lee** [AgNO3/jcifs-ng#313]
This isn't an issue, but a question about when the next planned release of this project will be, or if there is a set release schedule? I apologize if this isn't the right venue to ask this.

**Comment by mbechler** [comment]
There is no specific schedule. Usually a time comes around when there are both sufficient changes and ongoing efforts come to completion. You are probably asking because of the treeId changes, as this is a blocker for some people, yeah, I probably should do (or rather should have done) one soon.

**Comment by eg-lee** [comment]
Ok, thank you for response.

**Comment by mbechler** [comment]
New release pushed.
