### ISSUE TITLE
Does JCIFS support SMB3?

### ISSUE THREAD

**Issue by munirajtomar** [AgNO3/jcifs-ng#32]
we are going to use content-fetch and delete action on remote files from a smb3 devices. Still there is an open questions around JCIFS support for SMB3. Can you guys please confirm. Thanks in advance.

**Comment by mbechler** [comment]
master branch has some experimental basic SMB3 support - which should allow connecting to such servers - if you enable it by config. Still lacks support for SMB encryption - I have a not-fully-working prototype for that, but I cannot make any promised when it will be ready.
