### ISSUE TITLE
Do we have a method to determine the type of server, such as Windows, NAS, Mac, Linux....

### ISSUE THREAD

**Issue by rongway777** [AgNO3/jcifs-ng#327]
I want to know what type of server I am connected to. Is there an API? Thanks in advance

**Comment by mbechler** [comment]
That kind of information is not provided over SMB. There may be some server type/version information available via NBNS browsing, but that is neither exposed by the library, nor would I recommend relying on it, as the mechanism is deprecated and disabled by default on recent windows versions. Haven't checked, maybe there is a RPC API that could be used for some of the platforms.

**Comment by rongway777** [comment]
I will try to study in the direction you said, and thank you for your reply
