### ISSUE TITLE
java.lang.NullPointerException and/or MalformedURLException when calling SMBFile.listFiles() and enableSMB2=false

### ISSUE THREAD

**Issue by justoperez** [AgNO3/jcifs-ng#33]
I'm getting the following NPE when I call SMBFile.listFiles() against a Windows 2008 Server R2. I'm running against SMB1, so I disabled SMB2 with the property jcifs.smb.client.enableSMB2=false. I also made sure that jcifs.smb.client.disableSMB1=false.

Exception in thread "main" java.lang.NullPointerException
    at jcifs.smb.DirFileEntryEnumIteratorBase.advance(DirFileEntryEnumIteratorBase.java:144)
    at jcifs.smb.DirFileEntryEnumIterator1.open(DirFileEntryEnumIterator1.java:94)
    at jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67)
    at jcifs.smb.DirFileEntryEnumIterator1.<init>(DirFileEntryEnumIterator1.java:46)
    at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:198)
    at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:253)
    at jcifs.smb.SmbFile.listFiles(SmbFile.java:1271)
    at TestJCIFS_readdir.main(TestJCIFS_readdir.java:63)

My test is simple. Given a top directory, traverse the two subdirectories and listFiles().

I added some debug code and noticed that the data is being asynchronously loaded by this Transport thread:

jcifs.internal.smb1.trans2.Trans2FindFirst2Response.readDataWireFormat(Trans2FindFirst2Response.java:143), jcifs.internal.smb1.trans.SmbComTransactionResponse.readBytesWireFormat(SmbComTransactionResponse.java:315), 
jcifs.internal.smb1.ServerMessageBlock.decode(ServerMessageBlock.java:1195), 
jcifs.internal.smb1.trans.SmbComTransactionResponse.decode(SmbComTransactionResponse.java:240), 
jcifs.smb.SmbTransportImpl.doRecvSMB1(SmbTransportImpl.java:1228), 
jcifs.smb.SmbTransportImpl.doRecv(SmbTransportImpl.java:1097), 
jcifs.util.transport.Transport.loop(Transport.java:459), jcifs.util.transport.Transport.run(Transport.java:762), java.lang.Thread.run(Thread.java:785)]

And the DirFileEntryEnumIteratorBase.advance() call is getting the results here ->

protected final FileEntry advance ( boolean last ) throws CIFSException {
        FileEntry[] results = getResults(); <- HERE. Null is being returned
        while ( this.ridx < results.length ) {
            FileEntry itm = results[ this.ridx ];
            this.ridx++;
            if ( filter(itm) ) {
                return itm;
            }
        }

But the results haven't been loaded yet by the asynchronous call to Trans2FindFirst2Response.readDataWireFormat() here ->

       setResults(results); <- HERE

        /*
         * last nextEntryOffset for NT 4(but not 98) is 0 so we must
         * use dataCount or our accounting will report an error for NT :~(
         */
        System.out.println("readDataWireFormat:data count="+getDataCount());
        return getDataCount();

So there seems to be a synchronization problem between the data (results) not being loaded and set, and the iterator trying to get the results (when it has not been set yet by the readDataWireFormat() call).

Is there a synchronization bug between these two pieces of code?

Thanks in advance.

**Comment by justoperez** [comment]
I also wanted to point out that another symptom of the synchronization problem between the iterator and the background Transport thread, is that the iterator sometimes will log MalformedURLException messages.

2018-02-02 21:15:29 ERROR FileEntryAdapterIterator:87 - Failed to create child URL
java.net.MalformedURLException: Name must not be empty
    at jcifs.smb.SmbFile.checkName(SmbFile.java:656)
    at jcifs.smb.SmbFile.<init>(SmbFile.java:533)
    at jcifs.smb.DirFileEntryAdapterIterator.adapt(DirFileEntryAdapterIterator.java:57)
    at jcifs.smb.FileEntryAdapterIterator.advance(FileEntryAdapterIterator.java:82)
    at jcifs.smb.FileEntryAdapterIterator.<init>(FileEntryAdapterIterator.java:55)
    at jcifs.smb.DirFileEntryAdapterIterator.<init>(DirFileEntryAdapterIterator.java:37)
    at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:198)
    at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:253)
    at jcifs.smb.SmbFile.listFiles(SmbFile.java:1271)
    at TestJCIFS_readdir.main(TestJCIFS_readdir.java:49)

The reason is that the iterator calls send() which causes a release of the cached buffer in the response SmbTransport object. 

BufferCacheImpl:relaseBuffer buffer=1065011537, stack=[java.lang.Thread.getStackTraceImpl(Native Method), java.lang.Thread.getStackTrace(Thread.java:1117), jcifs.smb.BufferCacheImpl.releaseBuffer(BufferCacheImpl.java:95), jcifs.smb.SmbTransportImpl.sendComTransaction(SmbTransportImpl.java:1610), jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1463), jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397), jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465), jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:396), jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:313), jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294), jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130), jcifs.smb.DirFileEntryEnumIterator1.open(DirFileEntryEnumIterator1.java:67), jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67), jcifs.smb.DirFileEntryEnumIterator1.<init>(DirFileEntryEnumIterator1.java:46), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:198), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:253), jcifs.smb.SmbFile.listFiles(SmbFile.java:1271), TestJCIFS_readdir.main(TestJCIFS_readdir.java:49)]

But the Transport background thread is still using this same cache buffer to decode the data and return/set the results (FileEntry[]). 

For example, in my debugging session, there are four FileEntry that are returned. I printed these four entries as they were being populated in jcifs.internal.smb1.trans2.Trans2FindFirst2Response.readDataWireFormat(). The first two have a filename and valid fields, but the last two have null filenames and zeroed fields. I dumped the buffer right when readDataWireFormat() was called, so I know the buffer looked good and contained the right information. It was in the middle of readDataWireFormat(), when it was decoding the buffer into FileEntry objects, that the buffer was zeroed out. Here is my debug output, where you can see that the first two entries populated and the last two entries basically zeroed out:

readDataWireFormat:result[0]=SmbFindFileBothDirectoryInfo[nextEntryOffset=96,fileIndex=0,creationTime=Wed Nov 15 02:06:57 UTC 2017,lastAccessTime=Thu Feb 01 03:06:48 UTC 2018,lastWriteTime=Thu Feb 01 03:06:48 UTC 2018,changeTime=Thu Feb 01 03:06:48 UTC 2018,endOfFile=0,allocationSize=0,extFileAttributes=16,eaSize=0,shortName=,filename=.]

readDataWireFormat:result[1]=SmbFindFileBothDirectoryInfo[nextEntryOffset=104,fileIndex=0,creationTime=Wed Nov 15 02:06:57 UTC 2017,lastAccessTime=Thu Feb 01 03:06:48 UTC 2018,lastWriteTime=Thu Feb 01 03:06:48 UTC 2018,changeTime=Thu Feb 01 03:06:48 UTC 2018,endOfFile=0,allocationSize=0,extFileAttributes=16,eaSize=0,shortName=,filename=..]

readDataWireFormat:result[2]=SmbFindFileBothDirectoryInfo[nextEntryOffset=0,fileIndex=0,creationTime=Mon Jan 01 00:00:00 UTC 1601,lastAccessTime=Mon Jan 01 00:00:00 UTC 1601,lastWriteTime=Mon Jan 01 00:00:00 UTC 1601,changeTime=Mon Jan 01 00:00:00 UTC 1601,endOfFile=0,allocationSize=0,extFileAttributes=0,eaSize=0,shortName=,filename=]

readDataWireFormat:result[3]=SmbFindFileBothDirectoryInfo[nextEntryOffset=0,fileIndex=0,creationTime=Mon Jan 01 00:00:00 UTC 1601,lastAccessTime=Mon Jan 01 00:00:00 UTC 1601,lastWriteTime=Mon Jan 01 00:00:00 UTC 1601,changeTime=Mon Jan 01 00:00:00 UTC 1601,endOfFile=0,allocationSize=0,extFileAttributes=0,eaSize=0,shortName=,filename=]

By the way, the cached buffer being released by the iterator (send()) and being used by readWireFormat() was acquired by the iterator in this call:

getBuffer buffer=1065011537, stack=[java.lang.Thread.getStackTraceImpl(Native Method), java.lang.Thread.getStackTrace(Thread.java:1117), jcifs.smb.BufferCacheImpl.getBuffer(BufferCacheImpl.java:76), jcifs.smb.SmbTransportImpl.setupBuffers(SmbTransportImpl.java:1617), jcifs.smb.SmbTransportImpl.sendComTransaction(SmbTransportImpl.java:1531), jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1463), jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:397), jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:465), jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:396), jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:313), jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:294), jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130), jcifs.smb.DirFileEntryEnumIterator1.open(DirFileEntryEnumIterator1.java:67), jcifs.smb.DirFileEntryEnumIteratorBase.<init>(DirFileEntryEnumIteratorBase.java:67), jcifs.smb.DirFileEntryEnumIterator1.<init>(DirFileEntryEnumIterator1.java:46), jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:198), jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:253), jcifs.smb.SmbFile.listFiles(SmbFile.java:1271), TestJCIFS_readdir.main(TestJCIFS_readdir.java:49)]

So again, there seems to be a disconnect between the iterator and the background Transport thread in using buffers and setting/accessing FileEntry[] results in a timely/synchronized manner.

Any help you can provide is greatly appreciated.

**Comment by mbechler** [comment]
Thanks so much for debugging that. The MalformedURLException in fact turned up once before in #18 but I was unable to reproduce it back then and the reporter closed the issue and I forgot about it.

SmbTransportImpl.sendComTransaction should in fact wait for the response to be received and decoded so that it is okay to release the buffer at that point. That waiting seems to have been the issue here.

(Apart from the two issues you encoutered this also seems to have cause some intermittent failures getting DFS referrals)

**Comment by justoperez** [comment]
Hello,

Thank you for the quick reply and fix. But although your changes do make the code safer, the synchronization problem and overwriting of the response buffer in the Trasnport receiving loop by the SmbTransportImpl::sendCommTransaction() is still occurring. Your changes actually make the synchronization error harder to reproduce :)

The good thing is that with your fixes, I was able to understand how the synchronization (wait/notify) is supposed to work.

I believe I have a fix that I would like you to review.

The problem is in SmbCommTransactionResponse::readBytesWireFormat(), 

if ( this.parametersDone && this.dataDone ) {
//      	this.hasMore = false; // BAD PLACE
            readParametersWireFormat(this.txn_buf, this.bufParameterStart, this.totalParameterCount);
            readDataWireFormat(this.txn_buf, this.bufDataStart, this.totalDataCount);
            this.hasMore = false; // SET HERE after readDataWireFormat() is done with the resp.txn_buf buffer
        }

The this.hasMore needs to be set after readDataWireFormat() is called, otherwise, the sender can wake up, check that resp.received=true and resp.hasMore = false and exit SmbTransportImpl:sendComTransaction(), thus releasing/zeroing the resp.txn_buf.

In my test run, the Transport.loop() received two messages. After executing the first doRecv(), the resp.received was set to true (response.received()). Then doRecv() is called on the second message. 

Meanwhile, the sender wakes up because of the notify in response.received() and exits the while loop because received=true and hasMore=false even though readDataWireFormat() is still executing and loading the information from the resp.txn_buf.

               /*
                 * Receive multiple fragments
                 */
                synchronized ( resp ) {
                    while ( !resp.isReceived() || resp.hasMoreElements() ) { // exits this loop even though readDatawireFormat() is still executing in the Transport.loop()

         ....
         getContext().getBufferCache().releaseBuffer(resp.releaseBuffer()); // releases resp.txn_buf :(

Can you please review my fix and let me know whether I'm missing anything else? And if you agree merge to the master code.

If you have any questions please let me know.

Thanks!

**Comment by mbechler** [comment]
Thanks! Looks good to me. I also sprinkled around some volatile around to make sure that these are propagated between threads properly which may be another issue. CI build running, fingers crossed.
