### ISSUE TITLE
Problem trying to acces shared folder with a Office 365 environment.

### ISSUE THREAD

**Issue by MacPaiva** [AgNO3/jcifs-ng#336]
Hi!

I'm trying to save a CSV file in a Windows Server shared folder which basically I need to pass these infos:

String domain = "" (empty)
String username = "email@emaildomain.com"
String password = "password"

But everytime I call the NtlmPasswordAuthenticator(domain, username, password), the library add the "emaildomain.com"as the connection domain, and remove the "@emaildomain.com" from the username.

The problem is, to connect in a Office 365 shared folder, I need the domain to stay empty and the username to stay "email@emaildomain.com".

Does anyone now if there is a fix for that?

Thank you very much.

**Comment by mbechler** [comment]
That looks to be a bit of an oversight on my side, unfortunately not easily fixable without potentially breaking other user's code. Will have to add yet another constructor to allow avoiding that.

Working around that issue does not look straight forward, using the URL userInfo-based constructor exposed via the legacy NtlmPasswordAuthentication seems to be the only way via official APIs, but that's not a great option either.  Probably easier to just forcibly set the username and domain fields via reflection.
