### ISSUE TITLE
how to do the test？

### ISSUE THREAD

**Issue by fengyingkong** [AgNO3/jcifs-ng#339]
done for KerberosTest.java . but ..
java.lang.Exception: No tests found matching testKRB with any parameter from org.junit.runner.Request$1@59f99ea
![image](https://github.com/AgNO3/jcifs-ng/assets/32350484/3f36908b-55fe-49b9-9ce6-759ca9f0475e)

**Comment by mbechler** [comment]
What are you trying to run/achieve? Running most test cases requires providing server configurations. Unfortunately this is not really documented, but I can provide some examples if you like.

**Comment by fengyingkong** [comment]
yes, please provide some examples for me.  
thank you.

**Comment by mbechler** [comment]
You can provide one or a whole set of server configs (.conf extensions) through the _test.config.file_ or _test.config.dir_ system properties.
Two examples from my test setup are below. Some settings, e.g. the SIDs are not totally necessary, but enable some additional tests.

```
# No SMB1 server support for this one
test.mutations.exclude=noNTStatus,noSigning,forceSigning,legacyAuth,noUnicode,forceUnicode,noNTStatus,noNTSmbs,noUnicode-cp850,noUnicode-windows-1252,noLargeReadWrite,smb1

test.server=w2k19-single-dc.w2k19single.springfield
test.user.name=test1 
test.user.domain=W2K19SINGLE.SPRINGFIELD
test.user.sdomain=W2K19SINGLE
test.user.password=<pw>
test.user.sid=S-1-5-21-3857529893-3941372170-2395057007-1103
test.share.guest=test-guest

test.domain=W2K19SINGLE.SPRINGFIELD
test.domain.netbios=W2K19SINGLE
test.domain.dc=w2k19-single-dc.w2k19single.springfield
test.domain.sid=S-1-5-21-3857529893-3941372170-2395057007
```

```
test.mutations.exclude=noNTStatus
test.skip.hidden=true

test.user.name=test1
test.user.password=<pw>
test.user.domain=samba4ad.springfield
test.user.sdomain=SAMBA4AD

test.share.main.url=smb://samba4ad.springfield/dfs/dfstest/
test.share.dfsroot.url=smb://samba4ad.springfield/dfs/


# New file server does not seem to support guest auth
#test.share.guest=test-guest

test.server=samba4-dc.samba4ad.springfield
test.domain=samba4ad.springfield
test.domain.netbios=SAMBA4AD


jcifs.smb.client.ignoreCopyToException=true
```

**Comment by fengyingkong** [comment]
thank you very much.
