### ISSUE TITLE
The 2.0 series is now discontinued?

### ISSUE THREAD

**Issue by AlBundy33** [AgNO3/jcifs-ng#341]
From readme:
_The 2.0 series is now discontinued._

Does this mean the project is dead? 🤔

**Comment by mbechler** [comment]
The current release versions are 2.1.*, so no, not dead. But not much progress for quite a while, either.

**Comment by AlBundy33** [comment]
Ahh - it's only 2.0.x that is discontinued and not the whole project.
Then this was just a misunderstanding. 😄 

Thanks for clarification 👍
