### ISSUE TITLE
The documentation is not helpful

### ISSUE THREAD

**Issue by anirudh-kac** [AgNO3/jcifs-ng#346]
I want to use this library in one of my Android applications but I'm unable to find any proper guide or documentation on the usage of this library. Can somone please help me with resources for the same ?

**Comment by mbechler** [comment]
Are you looking for something specific? There is no "Getting started" guide or something alike. The javadoc for jcifs.SmbResource and jcifs.smb.SmbFile and jcifs.Configuration covers some basics. I'd also recommend looking at the test cases, there you should find usage examples for most if not all features.

**Comment by anirudh-kac** [comment]
Thanks!
