### ISSUE TITLE
Android SmbFile.length() return incorrect size of file.

### ISSUE THREAD

**Issue by konrofun** [AgNO3/jcifs-ng#355]
Hello,
I want to download files from a shared folder on Windows 10 to my Android client. However, every time I use smbfile.length(), it returns 4. This is my code. How can I get the correct file size?

private CIFSContext getCIFSContextInstance() {
	try {
		CIFSContext baseCxt = new BaseContext(new PropertyConfiguration(System.getProperties()));
		NtlmPasswordAuthenticator auth = new NtlmPasswordAuthenticator(userName, password);
		return baseCxt.withCredentials(auth);
	} catch (CIFSException e) {
		e.printStackTrace();
	}
	return null;
}

public void doDownload() {
	executorService.execute(new Runnable() {
		@Override
		public void run() {
			try {
				String localFilePath = "/storage/emulated/0/Download/1.png";
				String smbRemoteFilePath = "smb://192.168.x.x/share/1.png";
				
				SmbFile smbFile = new SmbFile(smbRemoteFilePath, getCIFSContextInstance());
				smbFile.connect();

				if (smbFile == null) {
					Timber.d("Shared file not exist.");
					return;
				}
				long remoteSize = smbFile.length();
				long contentLengthLong = smbFile.getContentLengthLong();

				try (SmbFileInputStream smbFileInputStream = new SmbFileInputStream(smbFile)) {
					File localFile = new File(localFilePath);
					FileOutputStream fileOutputStream = new FileOutputStream(localFile);

					byte[] buffer = new byte[4096];
					int length = 0;
					while ((length = smbFileInputStream.read(buffer)) > 0) {
						fileOutputStream.write(buffer, 0, length);
					}

					smbFileInputStream.close();
					fileOutputStream.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	});
}

**Comment by mbechler** [comment]
Both

```
long remoteSize = smbFile.length();
long contentLengthLong = smbFile.getContentLengthLong();
```

should return the file size reported by the server. 
Can you get a network capture (PCAP) of or check yourself what is reported in the corresponding SMB_OPEN and SMB_CLOSE packets?
