### ISSUE TITLE
Chicken/egg relationship between CIFSContext and credentials

### ISSUE THREAD

**Issue by svella** [AgNO3/jcifs-ng#36]
The relationship between CIFSContext and credentials represented by this idiom seems strange and problematic to me.

```
ctx.withCredentials(
    new NtlmPasswordAuthentication(
        ctx,
        getTestUserDomain(),
        getTestUser(),
        getTestUserPassword()))
```
We create credentials that point to a context, but then we create a wrapper for the original context that points back to the credentials. So we can navigate from the wrapper to the credentials, navigate from the credentials to the original context, but from there we can't navigate back to the credentials. It seems like this is bound to cause an issue at some point.

**Comment by mbechler** [comment]
Yes, that design is quite unfortunate and I don't like it much either.
It's mostly a result from the desire to stay backward compatible (fill in the defaults from the configuration), also it's a bit problematic that removing the context from the NtlmPasswordAuthentication will result in the original signature.

Probably should just have replaced NtlmPasswordAuthentication with a completely new class.

Question is how to get rid of it without causing to much trouble. It may be possible to introduce a new super type that just has the basics and deprecate NtlmPasswordAuthentication - let me think about that a bit.
