### ISSUE TITLE
File Transfer Issue with smbOutputStream Using Windows-1252 Encoding

### ISSUE THREAD

**Issue by NicoG27** [AgNO3/jcifs-ng#361]
I am experiencing an issue with file transfers using smbOutputStream when the encoding is set to Windows-1252. While the transfer does complete successfully, the resulting file always ends up being encoded in UTF-8 or UTF-16, regardless of the specified encoding.

```
  public void writeFile(String filePath, String content) {
        log.info("Writing file {}", filePath);
        try (SmbFile file = newSmbFile(filePath); SmbFileOutputStream outputStream = newSmbFileOutputStream(file)) {
            outputStream.write(content.getBytes("Windows-1252"));
        } catch (MalformedURLException | SmbException e) {
            log.error(e.getMessage());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

```
    private SmbFileOutputStream newSmbFileOutputStream(SmbFile smbFile) throws SmbException {
        return new SmbFileOutputStream(smbFile);
    }

    private SmbFile newSmbFile(String filename) throws MalformedURLException {
        return new SmbFile(filename, newCifsContext());
    }
```

**Comment by smbproton** [comment]
@NicoG27 your file encoding should not be altered with https://t.ly/aK8-b

**Comment by mbechler** [comment]
@smbproton I will not tolerate ads for your commercial product on this bug tacker. Comment deleted. Do you have anything of value to add?

@NicoG27 Does the closing mean you figured it out? The APIs/library/protocol really only deal in binary data, so unless a server is doing something funky I don't see how this would happen. If there still is an issue try using a FileOutputStream instead to rule out client/caller side issues.

**Comment by smbproton** [comment]
I agree that file encoding discrepancies like this typically stem from how the data is handled client-side. Investigating how the encoding is applied before the data is passed to smbOutputStream can help identify the root cause. If switching to FileOutputStream solves the issue, it might suggest that smbOutputStream is altering the data in some unexpected way.
HTH
