### ISSUE TITLE
Change logging to use log4j2 or slf4j 

### ISSUE THREAD

**Issue by ullgren** [AgNO3/jcifs-ng#4]
Current dependency on the [obsolete](https://logging.apache.org/log4j/1.2/) log4j 1.x is not optimal since it will [not work anymore in java 9](https://blogs.apache.org/logging/entry/moving_on_to_log4j_2).

It would be much better to use a log facade such as [slf4j](http://www.slf4j.org/) or atleast migrate to log4j2.

**Comment by mbechler** [comment]
Scheduling that for an upcoming point release. SLF4J is probably the better choice as it removes the dependency on the logger implementation - let's do that.

**Comment by mbechler** [comment]
1.6/2.0 got SLF4J
