### ISSUE TITLE
Is SMB2 v2.002 (Windwos 2008 server) supported with jcifs.smb.client.enableSMB2=true?

### ISSUE THREAD

**Issue by thanh-vn** [AgNO3/jcifs-ng#44]
I tried to connect to Windows 2008 server with jcifs.smb.client.enableSMB2=true and got jcifs.smb.SmbException: This client is not compatible with the server.
Also tried with the other signing (jcifs.smb.client.signingEnforced, jcifs.smb.client.signingPreferred) properties matching with the settings on the server and got the same error.

From Microsoft, the first release of Windows 2008 supports SMB2 **v2.002**.  I see jcifs-ng states 'SMB2 (**2.02** protocol level) support'.  Does that mean for Windows 2008, it only works with jcifs.smb.client.enableSMB2=false ?  (I tried with SMB1 and it worked).

Thanks,

**Comment by mbechler** [comment]
Can you get me a packet trace to see what is going on there. Best guess would be that this might be related to IPC signing as well (like #40, e.g. when trying to resolve DFS links).

**Comment by thanh-vn** [comment]
Hi,
Included the trace, thanks for looking at the issue.  
[issue44.zip](https://github.com/AgNO3/jcifs-ng/files/1717399/issue44.zip)

**Comment by mbechler** [comment]
Hm, I just see a single Negotiate Request and no answer to that and then the client confirming a connection reset. Not sure whether there is something wrong with the packat capture, or it's just MS Message Analyzer being buggy. Can you get me a proper packet trace (PCAP please). Debug log might be helpful, too.

**Comment by thanh-vn** [comment]
Thanks for your response.  Included is the trace with SMb1 and SMB2enable.  
[issue44-217.zip](https://github.com/AgNO3/jcifs-ng/files/1733795/issue44-217.zip)

**Comment by mbechler** [comment]
I think that is the same issue as #26. Can you check that d2d7fc8efc93a4a3f227dca609b09377fe514725 works for you, too.

**Comment by thanh-vn** [comment]
Thanks, that works for me.
