### ISSUE TITLE
SMB2 SmbRandomAccessFile.write() performance

### ISSUE THREAD

**Issue by justoperez** [AgNO3/jcifs-ng#47]
Good morning! It's me again. 

I have a question about SMB2 performance for the SMbRandomAccessFile.write() API. We have noticed that the performance is about twice compared to using the "old" SMB1 jcifs-1.3.18-flx.1.jar library. The performance seems to "improve somewhat" when writing larger number of bytes.

For example, when writing a few bytes (eg. 1, 2 or < 13 bytes), the SMB2 write() takes on average 4-5 ms, whereas the jcifs-1.3.18 library takes ~2ms. I'm thinking that there is some "overhead" that is being paid in the SMB2 write() (or transport) code which 'shows more' when writing a small number of bytes.

I haven't added debug timing statements to the write() call stack yet to determine where that overhead may be coming from. I wanted to ask you if you had an idea or orient me on that part of the code to look.

When writing larger number of bytes at a time, the performance tends to improve, but I assume it's because 'this overhead' becomes a smaller piece of the overall write() time.

Any ideas or suggestions that would help me know which part of the code I should investigate, will be greatly appreciated.

Thanks in advance,

Justo

PS. We've also noticed that other APIs such as file open/create/mkdir also run 1-3 ms slower compared to their jcifs-1.3.18 counterparts.

**Comment by mbechler** [comment]
Generally speaking, such small writes are going to be quite inefficient in SMB.

A good start may be to compare SMB1 performance first. The resource tracking code might have introduced a tiny bit of overhead, but I don't think that should be noticable. Another thing to check if there is a noticable difference is whether maybe signing is correctly enabled with jcifs-ng but was not for original jcifs.

When it comes to SMB2 performance, you really can't compare that with SMB1 as it's a quite different protocol. The simple write in RandomAccessFile should only be a a single message but has 58 bytes of header overhead in SMB1 compared to 112 byte in SMB2. Again, you should also check whether signing is enabled in one case but not the other.

**Comment by justoperez** [comment]
As always, thank you for your reply and insight. I will investigate. For now, I'm closing this issue.
