### ISSUE TITLE
Fix for thread leak problem missing

### ISSUE THREAD

**Issue by tfleis** [AgNO3/jcifs-ng#6]
The following fix is missing in your version of jcifs:

http://samba.2283325.n4.nabble.com/Thread-leak-problem-on-connect-timeout-tp2515434p2515435.html

The modification under 3) is missing.

**Comment by mbechler** [comment]
Thanks for the pointer. 

I do however believe that the better fix is to properly interrupt and join the thread on failure as that leaves less room for error and also will probably fail faster in other connection error scenarios (with just the wait() I think this could take much longer than the desired connection timeout).

Just pushed an alternative fix for the issue, would be great if you could verify that this fixes it, too.

**Comment by tfleis** [comment]
Your last commits fixed the thread leak. When do you plan to release it?

**Comment by mbechler** [comment]
I'd like to see whether there is some response on #5 first, but probably some time this week.

**Comment by mbechler** [comment]
Just pushed the release, should arrive shortly on maven central.
