### ISSUE TITLE
jcifs.smb.SmbException: TreeID is NULL

### ISSUE THREAD

**Issue by Sentaroh** [AgNO3/jcifs-ng#63]
Jcifs.smb.SmbException: TreeID is NULL occurred in the following code. However, jcifs - 1.3.17 does not raise an exception. In SmbTreeImpl.java I think it is necessary to make TreeID recognize 0.
(https://github.com/Sentaroh/jcifs-ng-clone/commit/4e1be0d5a8d700b2afab10bd2779f386a3e36ba1)

jcifs-ng code

        System.getProperties().setProperty("jcifs.smb.client.ipcSigningEnforced", "false");
        System.getProperties().setProperty("jcifs.smb.client.minVersion", "SMB1");
        System.getProperties().setProperty("jcifs.smb.client.maxVersion", "SMB1");

        BaseContext bc = new BaseContext(new PropertyConfiguration(System.getProperties()));
        NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication(bc, "","gw","gw");
        CIFSContext ct = bc.withCredentials(creds);

        SmbFile sl = new SmbFile("smb://192.168.200.254/", ct);
        SmbFile fl = new SmbFile("smb://192.168.200.254/GH-1/aa/", ct);
        try {
            String[] shares=sl.list();
            for(String item:shares) System.out.println( item );
            
            String[] files=fl.list();
            for(String item:files) System.out.println( item );
        } catch(SmbException e) {
        	System.out.println( e.getMessage()+", "+String.format("0x%h", e.getNtStatus() ));
        }

[main] WARN jcifs.smb.SmbTreeConnection - Referral failed, trying next
jcifs.smb.SmbException: TreeID is NULL
	at jcifs.smb.SmbTreeImpl.treeConnected(SmbTreeImpl.java:655)
	at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:624)
	at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:609)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:563)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:484)
	at jcifs.smb.SmbEnumerationUtil.doShareEnum(SmbEnumerationUtil.java:143)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:216)
	at jcifs.smb.SmbEnumerationUtil.list(SmbEnumerationUtil.java:241)
	at jcifs.smb.SmbFile.list(SmbFile.java:1133)
	at com.test.jcifs.TestJcifsNg.main(TestJcifsNg.java:30)
TreeID is NULL, 0xc0000001

jcifs-1.3.17 code

        NtlmPasswordAuthentication creds = new NtlmPasswordAuthentication("","gw","gw");
        SmbFile sl = new SmbFile("smb://192.168.200.254/", creds);
        SmbFile fl = new SmbFile("smb://192.168.200.254/GH-1/aa/", creds);
		
        try {
            String[] shares=sl.list();
            for(String item:shares) System.out.println( item );
            
            String[] files=fl.list();
            for(String item:files) System.out.println( item );
        } catch(SmbException e) {
        	System.out.println( e.getMessage()+", "+String.format("0x%h", e.getNtStatus() ));
        }

jcifs-ng packet
![image](https://user-images.githubusercontent.com/4037866/38124507-049b0ca0-341d-11e8-8e41-649790580e57.png)

jcifs-1.3.17 packet
![image](https://user-images.githubusercontent.com/4037866/38124471-cca37d96-341c-11e8-9929-deb535314b01.png)

[TID0_JCIFS-NG_WireShark_capture_file.ZIP](https://github.com/AgNO3/jcifs-ng/files/1862672/TID0_JCIFS-NG_WireShark_capture_file.ZIP)

**Comment by mbechler** [comment]
You are right, TID = 0 should be valid in SMB1 (it's invalid in SMB2). Should be fixed in master.

**Comment by Sentaroh** [comment]
thank you, the issue is resolved.
