### ISSUE TITLE
ETA for 2.0.6 release.

### ISSUE THREAD

**Issue by mdzhigarov** [AgNO3/jcifs-ng#66]
Hello,

I noticed that we already have a changelog for 2.0.6 in the commit history.
Does this mean that we'd be getting v2.0.6 anytime soon?

The reason I am asking is because we are planning a migration from jcifs to jcifs-ng but this change:
https://github.com/AgNO3/jcifs-ng/commit/0b6e7a616c40bd6cb146388eceafe3600aa13287
... is breaking us.

So I was hoping I could skip 2.0.5 and migrate directly to new NtlmPasswordAuthenticator class.

**Comment by mbechler** [comment]
2.0.6 will be coming today, however the change you mention will not go into there, only in the 2.1 major release. 
For 2.1 I would have liked to get the SMB encryption support working as well but I haven't gotten around to that for quite some while now. Maybe it is a good idea to postpone that and do a 2.1 release some time soon.
