### ISSUE TITLE
Understanding the notion of CIFSContext

### ISSUE THREAD

**Issue by mdzhigarov** [AgNO3/jcifs-ng#70]
This is rather a question than an issue.

I am trying to understand the notion of a CIFSContext.

In a typical protocol client application, a context holds the reference to the underlying network resource. 
If I then use the same context instance multiple times - I expect to get a shared connection.
If I use 2 separate context - I expect to get 2 completely separate sets of network resources.

Seems my understanding is not valid for jcifs-ng. 
My tests are showing that although I use 2 separate CIFSContexts, just 1 connection is established.
Is this expected?

What is the context for then?

**Comment by mbechler** [comment]
If you use two completely distinct CIFSContext that is the case, if you create two seperate instances of BaseContext, nothing will be shared between the two. SingletonContext however is a globally shared instance. The design allows customization so that different things can be shared if you desire so (say, e.g. the name service cache).

The other major function of CIFSContext is holding credentials. A scenario is creating multiple sessions  sharing the connections. For that one can create multiple derived contexts with different credentials.

Hope that helps.

**Comment by mdzhigarov** [comment]
That helps a lot, thanks!

How are credentials being shared exactly? In order to reuse them, does one have to use the same NtlmPasswordAuthenticator object instance?

Example:

```
NtlmPasswordAuthenticator auth1 = new NtlmPasswordAuthenticator("SUB", "m.dzhigarov", "test123");
NtlmPasswordAuthenticator auth2 = new NtlmPasswordAuthenticator("SUB", "m.dzhigarov", "test123");

CIFSContext context1 = SingletonContext.getInstance().withCredentials(auth1);
context1.getTransportPool().logon(context1, address);
context1.getTransportPool().logon(context1, address); // Would that have any effect?

CIFSContext context2 = SingletonContext.getInstance().withCredentials(auth2);
context2.getTransportPool().logon(context2, address);  // What about this?
context2.getTransportPool().logon(context2, address);
```

As you see, auth1 and auth2 are semantically the same - they are using the same domain/username/pass, but are 2 different object instances.

In this example I am using the same context instance (SingletonContext) but I am wrapping it in CIFSContextCredentialWrapper using the withCredentials() method, passing the 2 NtlmPasswordAuthenticator instances.

What I need to understand is - how many authentication attempts would be made in this case?
The first time I call `context1.getTransportPool().logon(context1, address);` I expect one authentication attempt.
Then on next line I call `context1.getTransportPool().logon(context1, address);` again. Would that produce a new auth attempt and if so - why? User "m.dzhigarov" has already been authenticated.

Next, I call `context2.getTransportPool().logon(context2, address);`. Same concern here - would that produce new auth attempt? Basically, it is for the same user (but different CIFSContextCredentialWrapper). Would jcifs-ng figure this out and reuse the auth information?
