### ISSUE TITLE
Support for FIPS 140-2 compliant JCE providers

### ISSUE THREAD

**Issue by djdkedev** [AgNO3/jcifs-ng#81]
Does Jcifs-ng provide any configuration to use  FIPS compilant Java Cryptography Extension (JCE) providers?
OR 
Does it allow to use FIPS compliant bouncy castle JCE provider?

Thanks,
Dhananjay

**Comment by mbechler** [comment]
If the FIPS approved version of bouncycastle is API compatible with recent regular BC versions then probably yes (have you actually tried?), otherwise no (and I'm not inclined to change that).

**Comment by djdkedev** [comment]
Thanks! 
It seems that API are not compatible.
