### ISSUE TITLE
readErrorResponse failed when response is not with structureSize 9

### ISSUE THREAD

**Issue by guybmayor** [AgNO3/jcifs-ng#84]
Hi,

I had a SMB2_IOCTL response msg that failed but I could not see in the logs the error so I found that in 
jcifs.internal.smb2.ServerMessageBlock2:readErrorResponse it referred only to messages with structureSize=9 so it throws SMBProtocolDecodingException with no reason.

please check my pull request [https://github.com/AgNO3/jcifs-ng/pull/83](url)

**Comment by mbechler** [comment]
The change should be fine to increase interoperability I guess, but can you provide details on the message/exchange? Maybe we are treating something as an error message that we shouldn't.

The documentation is in fact very clear about structureSize for error responses:

StructureSize (2 bytes): The server MUST set this field to 9, indicating the size of the response
structure, not including the header. The server MUST set it to this value regardless of how long
ErrorData[] actually is in the response being sent.

**Comment by mbechler** [comment]
Which IOCTL CtlCode is that and what is the error code?

On seconds thought, I don't think it is a good idea to just ignore that. If we just ignore that we end up not reading the complete response (as we don't know its proper length). If the message is signed or part of a compound chain that will go horribly wrong.

We should rather fix the actual issue. If this is pipe related (or possibly DFS) STATUS_BUFFER_OVERFLOW that should be covered by #92.

**Comment by guybmayor** [comment]
OK, so you can still read the structureSize, but check and throwing an exception if it's not equal to 9 because it's not supposed to be 9 on every message type.  Or did I understand something wrong?

**Comment by mbechler** [comment]
It is supposed to be 9 when the response is of the generic error message format. 49 probably indicates that it is an actual IOCTL response format (but with an error code). We have to make sure that we actually parse using the correct format or otherwise we are likely to end up with more subtle issues down the road.

Have you tried whether the changes from 2.0.7/2.1 fix this?

**Comment by guybmayor** [comment]
You are rigth, I miss the error message format. thx
