### ISSUE TITLE
Missing .conf files for unit tests

### ISSUE THREAD

**Issue by svella** [AgNO3/jcifs-ng#88]
I thought unit test were all passing until I discovered that they weren't action being run because they depend on a set of .conf files that are not part of the project. It would be nice to have at least templates for those so when I try to fix and submit bugs I can verify them existing the existing tests as well as new ones I might need to add.

**Comment by mbechler** [comment]
One I'm using that should cover most of the basics, hope that helps to get started:
```
test.user.name=test1
test.user.password=****
test.user.domain=SMBAD.SPRINGFIELD
test.user.sdomain=SMBAD

test.share.main.url=smb://smbad.springfield/dfs/dfstest/
test.share.dfsroot.url=smb://smbad.springfield/dfs/

test.server=homer.smbad.springfield
test.share.guest=test-guest
test.domain=smbad.springfield
test.domain.netbios=SMBAD


test.domain.dc=homer.smbad.springfield
test.domain.sid=S-1-5-21-18369567-3199046959-3522121319
test.user.sid=S-1-5-21-18369567-3199046959-3522121319-1103

#regular settings
#jcifs.smb.client.dfs.disabled=true

jcifs.netbios.wins=homer.smbad.springfield
```
